import { Router } from 'express';
import * as ctrl from '../controllers/detalleSaldo.js';
const router = Router();
router.get('/', ctrl.getAll);
router.get('/maquina/:maqId', ctrl.getByMachine);
router.get('/:id', ctrl.getById);
router.post('/', ctrl.create);
router.put('/:id', ctrl.updateUmbral);
router.put('/:id/umbral', ctrl.updateUmbral);
export default router;
