import { Router } from 'express';
import * as ctrl from '../controllers/membresia.js';
const router = Router();
router.get('/', ctrl.getAll);
router.get('/payment-candidates/search', ctrl.searchPaymentCandidates);
router.post('/validate-tag', ctrl.validateTag);
router.post('/validate-tag-exit', ctrl.validateTagExit);
router.get('/:id/history', ctrl.getHistory);
router.get('/:id/tag.pdf', ctrl.downloadTag);
router.post('/:id/register-payment', ctrl.registerPayment);
router.get('/:id', ctrl.getById);
router.post('/', ctrl.create);
router.put('/:id', ctrl.update);
export default router;
