import { Router } from 'express';
import * as ctrl from '../controllers/ticket.js';
const router = Router();
router.get('/', ctrl.getAll);
router.get('/:id', ctrl.getById);
router.get('/:id/comprobante.pdf', ctrl.downloadReceipt);
router.get('/:id/entrada.pdf', ctrl.downloadEntryTicket);
router.post('/quote', ctrl.quoteByCodigo);
router.post('/checkout', ctrl.checkout);
router.post('/exit-validate', ctrl.validateExit);
router.post('/entry', ctrl.generateEntry);
router.post('/', ctrl.create);
router.put('/:id', ctrl.update);
export default router;
