CREATE OR REPLACE PROCEDURE SP_ALERTA_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT ALE_ID, MAQ_ID, ALE_MOTIVO, ALE_DESCRIPCION, ALE_FECHA_HORA_GENERACION, EAL_ID, TAL_ID, ALE_FECHA_ATENCION
    FROM PAR_ALERTA;
END SP_ALERTA_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_ALERTA_GET_BY_ID (
    p_id IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT ALE_ID, MAQ_ID, ALE_MOTIVO, ALE_DESCRIPCION, ALE_FECHA_HORA_GENERACION, EAL_ID, TAL_ID, ALE_FECHA_ATENCION
    FROM PAR_ALERTA
    WHERE ALE_ID = p_id;
END SP_ALERTA_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_ALERTA_CREATE (
    p_ALE_ID IN NUMBER,
    p_MAQ_ID IN NUMBER,
    p_ALE_MOTIVO IN VARCHAR2,
    p_ALE_DESCRIPCION IN VARCHAR2,
    p_ALE_FECHA_HORA_GENERACION IN TIMESTAMP,
    p_EAL_ID IN NUMBER,
    p_TAL_ID IN NUMBER,
    p_ALE_FECHA_ATENCION IN TIMESTAMP
) AS
BEGIN
    INSERT INTO PAR_ALERTA (ALE_ID, MAQ_ID, ALE_MOTIVO, ALE_DESCRIPCION, ALE_FECHA_HORA_GENERACION, EAL_ID, TAL_ID, ALE_FECHA_ATENCION)
    VALUES (p_ALE_ID, p_MAQ_ID, p_ALE_MOTIVO, p_ALE_DESCRIPCION, p_ALE_FECHA_HORA_GENERACION, p_EAL_ID, p_TAL_ID, p_ALE_FECHA_ATENCION);
    COMMIT;
END SP_ALERTA_CREATE;
/

CREATE OR REPLACE PROCEDURE SP_ALERTA_UPDATE (
    p_id IN NUMBER,
    p_EAL_ID IN NUMBER,
    p_ALE_FECHA_ATENCION IN TIMESTAMP
) AS
BEGIN
    UPDATE PAR_ALERTA
    SET EAL_ID = p_EAL_ID,
        ALE_FECHA_ATENCION = p_ALE_FECHA_ATENCION
    WHERE ALE_ID = p_id;
    COMMIT;
END SP_ALERTA_UPDATE;
/
