CREATE OR REPLACE PROCEDURE SP_ALERTA_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT ALE_ID, MAQ_ID, ALE_MOTIVO, ALE_DESCRIPCION,
               ALE_FECHA_HORA_GENERACION, EAL_ID, TAL_ID, ALE_FECHA_ATENCION,
               ALE_USU_ID_RESOLVIO, ALE_DESCRIPCION_SOLUCION
        FROM PAR_ALERTA
        ORDER BY ALE_FECHA_HORA_GENERACION DESC;
END SP_ALERTA_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_ALERTA_GET_BY_ID (
    p_id     IN  VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT ALE_ID, MAQ_ID, ALE_MOTIVO, ALE_DESCRIPCION,
               ALE_FECHA_HORA_GENERACION, EAL_ID, TAL_ID, ALE_FECHA_ATENCION,
               ALE_USU_ID_RESOLVIO, ALE_DESCRIPCION_SOLUCION
        FROM PAR_ALERTA
        WHERE ALE_ID = p_id;
END SP_ALERTA_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_ALERTA_CREATE (
    p_ALE_ID                    IN VARCHAR2,
    p_MAQ_ID                    IN VARCHAR2,
    p_ALE_MOTIVO                IN VARCHAR2,
    p_ALE_DESCRIPCION           IN VARCHAR2,
    p_ALE_FECHA_HORA_GENERACION IN DATE,
    p_EAL_ID                    IN VARCHAR2,
    p_TAL_ID                    IN VARCHAR2,
    p_ALE_FECHA_ATENCION        IN DATE,
    p_ALE_USU_ID_RESOLVIO       IN NUMBER,
    p_ALE_DESCRIPCION_SOLUCION  IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_ALERTA (
        ALE_ID, MAQ_ID, ALE_MOTIVO, ALE_DESCRIPCION,
        ALE_FECHA_HORA_GENERACION, EAL_ID, TAL_ID, ALE_FECHA_ATENCION,
        ALE_USU_ID_RESOLVIO, ALE_DESCRIPCION_SOLUCION
    ) VALUES (
        p_ALE_ID, p_MAQ_ID, p_ALE_MOTIVO, p_ALE_DESCRIPCION,
        NVL(p_ALE_FECHA_HORA_GENERACION, SYSDATE), p_EAL_ID, p_TAL_ID, p_ALE_FECHA_ATENCION,
        p_ALE_USU_ID_RESOLVIO, p_ALE_DESCRIPCION_SOLUCION
    );
    COMMIT;
END SP_ALERTA_CREATE;
/

CREATE OR REPLACE PROCEDURE SP_ALERTA_UPDATE (
    p_id                 IN VARCHAR2,
    p_EAL_ID             IN VARCHAR2,
    p_ALE_FECHA_ATENCION IN DATE,
    p_ALE_USU_ID_RESOLVIO IN NUMBER,
    p_ALE_DESCRIPCION_SOLUCION IN VARCHAR2
) AS
BEGIN
    UPDATE PAR_ALERTA
    SET EAL_ID             = p_EAL_ID,
        ALE_FECHA_ATENCION = p_ALE_FECHA_ATENCION,
        ALE_USU_ID_RESOLVIO = p_ALE_USU_ID_RESOLVIO,
        ALE_DESCRIPCION_SOLUCION = p_ALE_DESCRIPCION_SOLUCION
    WHERE ALE_ID = p_id;
    COMMIT;
END SP_ALERTA_UPDATE;
/
