CREATE OR REPLACE PROCEDURE SP_BITACORA_INC_VEH_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT b.BIV_ID, b.BIV_DESCRIPCION, b.BIV_FECHA_HORA,
           b.VEH_ID, v.VEH_PLACA, mod.MOD_NOMBRE AS VEH_MODELO,
           mod.MAR_ID, mar.MAR_NOMBRE, mod.TVE_ID, tv.TVE_TIPO,
           v.COL_ID, col.COL_NOMBRE AS VEH_COLOR,
           b.INC_ID, i.INC_TIPO, i.INC_DESCRIPCION,
           b.BIV_RESUELTO, b.BIV_FECHA_RESOLUCION,
           b.USU_ID, u.USU_PRIMER_NOMBRE, u.USU_PRIMER_APELLIDO
    FROM PAR_BITACORA_INCIDENTE_VEHICULO b
    JOIN PAR_VEHICULO v ON b.VEH_ID = v.VEH_ID
    LEFT JOIN PAR_MODELO_VEHICULO mod ON v.MOD_ID = mod.MOD_ID
    LEFT JOIN PAR_MARCA_VEHICULO mar ON mod.MAR_ID = mar.MAR_ID
    LEFT JOIN PAR_TIPO_VEHICULO tv ON mod.TVE_ID = tv.TVE_ID
    LEFT JOIN PAR_COLOR_VEHICULO col ON v.COL_ID = col.COL_ID
    JOIN PAR_INCIDENTE i ON b.INC_ID = i.INC_ID
    LEFT JOIN PAR_USUARIO u ON b.USU_ID = u.USU_ID
    ORDER BY b.BIV_FECHA_HORA DESC;
END SP_BITACORA_INC_VEH_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_BITACORA_INC_VEH_GET_BY_ID (
    p_id IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT b.BIV_ID, b.BIV_DESCRIPCION, b.BIV_FECHA_HORA,
           b.VEH_ID, v.VEH_PLACA, mod.MOD_NOMBRE AS VEH_MODELO,
           mod.MAR_ID, mar.MAR_NOMBRE, mod.TVE_ID, tv.TVE_TIPO,
           v.COL_ID, col.COL_NOMBRE AS VEH_COLOR,
           b.INC_ID, i.INC_TIPO, i.INC_DESCRIPCION,
           b.BIV_RESUELTO, b.BIV_FECHA_RESOLUCION,
           b.USU_ID, u.USU_PRIMER_NOMBRE, u.USU_PRIMER_APELLIDO
    FROM PAR_BITACORA_INCIDENTE_VEHICULO b
    JOIN PAR_VEHICULO v ON b.VEH_ID = v.VEH_ID
    LEFT JOIN PAR_MODELO_VEHICULO mod ON v.MOD_ID = mod.MOD_ID
    LEFT JOIN PAR_MARCA_VEHICULO mar ON mod.MAR_ID = mar.MAR_ID
    LEFT JOIN PAR_TIPO_VEHICULO tv ON mod.TVE_ID = tv.TVE_ID
    LEFT JOIN PAR_COLOR_VEHICULO col ON v.COL_ID = col.COL_ID
    JOIN PAR_INCIDENTE i ON b.INC_ID = i.INC_ID
    LEFT JOIN PAR_USUARIO u ON b.USU_ID = u.USU_ID
    WHERE b.BIV_ID = p_id;
END SP_BITACORA_INC_VEH_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_BITACORA_INC_VEH_CREATE (
    p_BIV_ID               IN VARCHAR2,
    p_BIV_DESCRIPCION      IN VARCHAR2,
    p_BIV_FECHA_HORA       IN DATE,
    p_VEH_ID               IN VARCHAR2,
    p_INC_ID               IN VARCHAR2,
    p_BIV_RESUELTO         IN NUMBER,
    p_BIV_FECHA_RESOLUCION IN DATE,
    p_USU_ID               IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_BITACORA_INCIDENTE_VEHICULO (
        BIV_ID, BIV_DESCRIPCION, BIV_FECHA_HORA,
        VEH_ID, INC_ID, BIV_RESUELTO, BIV_FECHA_RESOLUCION, USU_ID
    )
    VALUES (
        p_BIV_ID, p_BIV_DESCRIPCION, p_BIV_FECHA_HORA,
        p_VEH_ID, p_INC_ID, p_BIV_RESUELTO, p_BIV_FECHA_RESOLUCION, p_USU_ID
    );
    COMMIT;
END SP_BITACORA_INC_VEH_CREATE;
/

CREATE OR REPLACE PROCEDURE SP_BITACORA_INC_VEH_RESOLVE (
    p_id                   IN VARCHAR2,
    p_BIV_RESUELTO         IN NUMBER,
    p_BIV_FECHA_RESOLUCION IN DATE,
    p_USU_ID               IN VARCHAR2
) AS
BEGIN
    UPDATE PAR_BITACORA_INCIDENTE_VEHICULO
    SET BIV_RESUELTO = p_BIV_RESUELTO,
        BIV_FECHA_RESOLUCION = p_BIV_FECHA_RESOLUCION,
        USU_ID = p_USU_ID
    WHERE BIV_ID = p_id;
    COMMIT;
END SP_BITACORA_INC_VEH_RESOLVE;
/
