CREATE OR REPLACE PROCEDURE SP_COBRO_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT COB_ID, COB_HORAS_TOTALES, TCO_ID, COB_MONTO_TOTAL, COB_MONTO_RECIBIDO, COB_VUELTO, COB_FECHA_HORA, COB_PROCESADO_MAQUINA, TAR_ID
    FROM PAR_COBRO;
END SP_COBRO_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_COBRO_GET_BY_ID (
    p_id IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT COB_ID, COB_HORAS_TOTALES, TCO_ID, COB_MONTO_TOTAL, COB_MONTO_RECIBIDO, COB_VUELTO, COB_FECHA_HORA, COB_PROCESADO_MAQUINA, TAR_ID
    FROM PAR_COBRO
    WHERE COB_ID = p_id;
END SP_COBRO_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_COBRO_CREATE (
    p_COB_ID IN NUMBER,
    p_COB_HORAS_TOTALES IN NUMBER,
    p_TCO_ID IN NUMBER,
    p_COB_MONTO_TOTAL IN NUMBER,
    p_COB_MONTO_RECIBIDO IN NUMBER,
    p_COB_VUELTO IN NUMBER,
    p_COB_FECHA_HORA IN TIMESTAMP,
    p_COB_PROCESADO_MAQUINA IN NUMBER,
    p_TAR_ID IN NUMBER
) AS
BEGIN
    INSERT INTO PAR_COBRO (COB_ID, COB_HORAS_TOTALES, TCO_ID, COB_MONTO_TOTAL, COB_MONTO_RECIBIDO, COB_VUELTO, COB_FECHA_HORA, COB_PROCESADO_MAQUINA, TAR_ID)
    VALUES (p_COB_ID, p_COB_HORAS_TOTALES, p_TCO_ID, p_COB_MONTO_TOTAL, p_COB_MONTO_RECIBIDO, p_COB_VUELTO, p_COB_FECHA_HORA, NVL(p_COB_PROCESADO_MAQUINA, 0), p_TAR_ID);
    COMMIT;
END SP_COBRO_CREATE;
/
