-- Alineado a PAR_ENTIDADES.sql: PAR_COBRO (COB_ID IDENTITY, TIC_ID NOT NULL, COB_NIT, UK_PAR_COBRO_TIC_ID).

CREATE OR REPLACE PROCEDURE SP_COBRO_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT COB_ID, TIC_ID, COB_NIT, COB_HORAS_TOTALES, TCO_ID, COB_MONTO_TOTAL,
               COB_MONTO_RECIBIDO, COB_VUELTO, COB_FECHA_HORA,
               COB_PROCESADO_MAQUINA, TAR_ID
        FROM PAR_COBRO
        ORDER BY COB_FECHA_HORA DESC;
END SP_COBRO_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_COBRO_GET_BY_ID (
    p_id     IN  NUMBER,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT COB_ID, TIC_ID, COB_NIT, COB_HORAS_TOTALES, TCO_ID, COB_MONTO_TOTAL,
               COB_MONTO_RECIBIDO, COB_VUELTO, COB_FECHA_HORA,
               COB_PROCESADO_MAQUINA, TAR_ID
        FROM PAR_COBRO
        WHERE COB_ID = p_id;
END SP_COBRO_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_COBRO_CREATE (
    p_TIC_ID                 IN NUMBER,
    p_COB_NIT                IN VARCHAR2,
    p_COB_HORAS_TOTALES      IN NUMBER,
    p_TCO_ID                 IN NUMBER,
    p_COB_MONTO_TOTAL        IN NUMBER,
    p_COB_MONTO_RECIBIDO     IN NUMBER,
    p_COB_VUELTO             IN NUMBER,
    p_COB_FECHA_HORA         IN DATE,
    p_COB_PROCESADO_MAQUINA  IN NUMBER,
    p_TAR_ID                 IN NUMBER,
    p_NEW_COB_ID             OUT NUMBER
) AS
BEGIN
    INSERT INTO PAR_COBRO (
        TIC_ID, COB_NIT, COB_HORAS_TOTALES, TCO_ID, COB_MONTO_TOTAL,
        COB_MONTO_RECIBIDO, COB_VUELTO, COB_FECHA_HORA, COB_PROCESADO_MAQUINA, TAR_ID
    ) VALUES (
        p_TIC_ID,
        p_COB_NIT,
        p_COB_HORAS_TOTALES,
        p_TCO_ID,
        p_COB_MONTO_TOTAL,
        p_COB_MONTO_RECIBIDO,
        p_COB_VUELTO,
        NVL(p_COB_FECHA_HORA, SYSDATE),
        NVL(p_COB_PROCESADO_MAQUINA, 0),
        p_TAR_ID
    )
    RETURNING COB_ID INTO p_NEW_COB_ID;
    COMMIT;
END SP_COBRO_CREATE;
/

CREATE OR REPLACE PROCEDURE SP_COBRO_UPDATE (
    p_id                    IN NUMBER,
    p_COB_PROCESADO_MAQUINA IN NUMBER
) AS
BEGIN
    UPDATE PAR_COBRO
    SET COB_PROCESADO_MAQUINA = NVL(p_COB_PROCESADO_MAQUINA, 0)
    WHERE COB_ID = p_id;
    COMMIT;
END SP_COBRO_UPDATE;
/
