CREATE OR REPLACE PROCEDURE SP_DETALLE_SALDO_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT ds.DSA_ID, ds.DSA_CANTIDAD, ds.DSA_SUBTOTAL,
           ds.SDI_ID, sd.SDI_TIPO, sd.SDI_VALOR,
           ds.MAQ_ID, m.MAQ_CODIGO
    FROM PAR_DETALLE_SALDO ds
    JOIN PAR_SALDO_DISPONIBLE sd ON ds.SDI_ID = sd.SDI_ID
    JOIN PAR_MAQUINA           m ON ds.MAQ_ID = m.MAQ_ID
    ORDER BY ds.DSA_ID;
END SP_DETALLE_SALDO_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_DETALLE_SALDO_GET_BY_ID (
    p_id IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT ds.DSA_ID, ds.DSA_CANTIDAD, ds.DSA_SUBTOTAL,
           ds.SDI_ID, sd.SDI_TIPO, sd.SDI_VALOR,
           ds.MAQ_ID, m.MAQ_CODIGO
    FROM PAR_DETALLE_SALDO ds
    JOIN PAR_SALDO_DISPONIBLE sd ON ds.SDI_ID = sd.SDI_ID
    JOIN PAR_MAQUINA           m ON ds.MAQ_ID = m.MAQ_ID
    WHERE ds.DSA_ID = p_id;
END SP_DETALLE_SALDO_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_DETALLE_SALDO_CREATE (
    p_DSA_ID       IN VARCHAR2,
    p_DSA_CANTIDAD IN NUMBER,
    p_DSA_SUBTOTAL IN NUMBER,
    p_SDI_ID       IN VARCHAR2,
    p_MAQ_ID       IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_DETALLE_SALDO (DSA_ID, DSA_CANTIDAD, DSA_SUBTOTAL, SDI_ID, MAQ_ID)
    VALUES (p_DSA_ID, p_DSA_CANTIDAD, p_DSA_SUBTOTAL, p_SDI_ID, p_MAQ_ID);
    COMMIT;
END SP_DETALLE_SALDO_CREATE;
/
