CREATE OR REPLACE PROCEDURE SP_DET_MAQ_TICKET_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT d.DMT_ID, d.DMT_TRANSACCION, d.DMT_HORA_TRANSACCION,
           d.TIC_ID, t.TIC_CODIGO,
           d.MAQ_ID, m.MAQ_CODIGO
    FROM PAR_DETALLE_MAQUINA_TICKET d
    JOIN PAR_TICKET  t ON d.TIC_ID = t.TIC_ID
    JOIN PAR_MAQUINA m ON d.MAQ_ID = m.MAQ_ID
    ORDER BY d.DMT_HORA_TRANSACCION DESC;
END SP_DET_MAQ_TICKET_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_DET_MAQ_TICKET_GET_BY_ID (
    p_id IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT d.DMT_ID, d.DMT_TRANSACCION, d.DMT_HORA_TRANSACCION,
           d.TIC_ID, t.TIC_CODIGO,
           d.MAQ_ID, m.MAQ_CODIGO
    FROM PAR_DETALLE_MAQUINA_TICKET d
    JOIN PAR_TICKET  t ON d.TIC_ID = t.TIC_ID
    JOIN PAR_MAQUINA m ON d.MAQ_ID = m.MAQ_ID
    WHERE d.DMT_ID = p_id;
END SP_DET_MAQ_TICKET_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_DET_MAQ_TICKET_CREATE (
    p_DMT_ID              IN VARCHAR2,
    p_DMT_TRANSACCION     IN VARCHAR2,
    p_TIC_ID              IN VARCHAR2,
    p_MAQ_ID              IN VARCHAR2,
    p_DMT_HORA_TRANSACCION IN TIMESTAMP
) AS
BEGIN
    INSERT INTO PAR_DETALLE_MAQUINA_TICKET (
        DMT_ID, DMT_TRANSACCION, TIC_ID, MAQ_ID, DMT_HORA_TRANSACCION
    )
    VALUES (
        p_DMT_ID, p_DMT_TRANSACCION, p_TIC_ID, p_MAQ_ID, p_DMT_HORA_TRANSACCION
    );
    COMMIT;
END SP_DET_MAQ_TICKET_CREATE;
/
