CREATE OR REPLACE PROCEDURE SP_DET_PAGO_MEM_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT DPM_ID, MEM_ID, PAG_ID, DPM_MES_CANCELADO
    FROM PAR_DETALLE_PAGO_MEMBRESIA
    ORDER BY DPM_ID;
END SP_DET_PAGO_MEM_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_DET_PAGO_MEM_GET_BY_ID (
    p_id IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT DPM_ID, MEM_ID, PAG_ID, DPM_MES_CANCELADO
    FROM PAR_DETALLE_PAGO_MEMBRESIA
    WHERE DPM_ID = p_id;
END SP_DET_PAGO_MEM_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_DET_PAGO_MEM_CREATE (
    p_DPM_ID            IN VARCHAR2,
    p_MEM_ID            IN VARCHAR2,
    p_PAG_ID            IN VARCHAR2,
    p_DPM_MES_CANCELADO IN NUMBER
) AS
BEGIN
    INSERT INTO PAR_DETALLE_PAGO_MEMBRESIA (DPM_ID, MEM_ID, PAG_ID, DPM_MES_CANCELADO)
    VALUES (p_DPM_ID, p_MEM_ID, p_PAG_ID, p_DPM_MES_CANCELADO);
    COMMIT;
END SP_DET_PAGO_MEM_CREATE;
/
