CREATE OR REPLACE PROCEDURE SP_ESTADO_MEMBRESIA_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT EME_ID, EME_ESTADO
    FROM PAR_ESTADO_MEMBRESIA;
END SP_ESTADO_MEMBRESIA_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_ESTADO_MEMBRESIA_GET_BY_ID (
    p_id IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT EME_ID, EME_ESTADO
    FROM PAR_ESTADO_MEMBRESIA
    WHERE EME_ID = p_id;
END SP_ESTADO_MEMBRESIA_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_ESTADO_MEMBRESIA_CREATE (
    p_EME_ID IN NUMBER,
    p_EME_ESTADO IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_ESTADO_MEMBRESIA (EME_ID, EME_ESTADO)
    VALUES (p_EME_ID, p_EME_ESTADO);
    COMMIT;
END SP_ESTADO_MEMBRESIA_CREATE;
/
