CREATE OR REPLACE PROCEDURE SP_ESTADO_TICKET_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT ETI_ID, ETI_ESTADO
    FROM PAR_ESTADO_TICKET
    ORDER BY ETI_ID;
END SP_ESTADO_TICKET_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_ESTADO_TICKET_GET_BY_ID (
    p_id IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT ETI_ID, ETI_ESTADO
    FROM PAR_ESTADO_TICKET
    WHERE ETI_ID = p_id;
END SP_ESTADO_TICKET_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_ESTADO_TICKET_CREATE (
    p_ETI_ID    IN VARCHAR2,
    p_ETI_ESTADO IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_ESTADO_TICKET (ETI_ID, ETI_ESTADO)
    VALUES (p_ETI_ID, p_ETI_ESTADO);
    COMMIT;
END SP_ESTADO_TICKET_CREATE;
/
