CREATE OR REPLACE PROCEDURE SP_ESTADO_MAQUINA_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT EMA_ID, EMA_ESTADO, EMA_DESCRIPCION
        FROM PAR_ESTADO_MAQUINA
        ORDER BY EMA_ID;
END SP_ESTADO_MAQUINA_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_ESTADO_MAQUINA_GET_BY_ID (
    p_id     IN  VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT EMA_ID, EMA_ESTADO, EMA_DESCRIPCION
        FROM PAR_ESTADO_MAQUINA
        WHERE EMA_ID = p_id;
END SP_ESTADO_MAQUINA_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_ESTADO_MAQUINA_CREATE (
    p_ema_id          IN VARCHAR2,
    p_ema_estado      IN VARCHAR2,
    p_ema_descripcion IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_ESTADO_MAQUINA (EMA_ID, EMA_ESTADO, EMA_DESCRIPCION)
    VALUES (p_ema_id, p_ema_estado, p_ema_descripcion);
    COMMIT;
END SP_ESTADO_MAQUINA_CREATE;
/

CREATE OR REPLACE PROCEDURE SP_ESTADO_MAQUINA_UPDATE (
    p_ema_id          IN VARCHAR2,
    p_ema_estado      IN VARCHAR2,
    p_ema_descripcion IN VARCHAR2
) AS
BEGIN
    UPDATE PAR_ESTADO_MAQUINA
    SET EMA_ESTADO      = p_ema_estado,
        EMA_DESCRIPCION = p_ema_descripcion
    WHERE EMA_ID = p_ema_id;
    COMMIT;
END SP_ESTADO_MAQUINA_UPDATE;
/

CREATE OR REPLACE PROCEDURE SP_ESTADO_MAQUINA_DELETE (
    p_id      IN  VARCHAR2,
    p_deleted OUT NUMBER
) AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM PAR_MAQUINA WHERE EMA_ID = p_id;
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar: existen máquinas con este estado');
    END IF;
    DELETE FROM PAR_ESTADO_MAQUINA WHERE EMA_ID = p_id;
    p_deleted := SQL%ROWCOUNT;
    COMMIT;
END SP_ESTADO_MAQUINA_DELETE;
/
