CREATE OR REPLACE PROCEDURE SP_ESTADO_ALERTA_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT EAL_ID, EAL_ESTADO, EAL_DESCRIPCION
    FROM PAR_ESTADO_ALERTA;
END SP_ESTADO_ALERTA_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_ESTADO_ALERTA_GET_BY_ID (
    p_id IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT EAL_ID, EAL_ESTADO, EAL_DESCRIPCION
    FROM PAR_ESTADO_ALERTA
    WHERE EAL_ID = p_id;
END SP_ESTADO_ALERTA_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_ESTADO_ALERTA_CREATE (
    p_EAL_ID IN NUMBER,
    p_EAL_ESTADO IN VARCHAR2,
    p_EAL_DESCRIPCION IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_ESTADO_ALERTA (EAL_ID, EAL_ESTADO, EAL_DESCRIPCION)
    VALUES (p_EAL_ID, p_EAL_ESTADO, p_EAL_DESCRIPCION);
    COMMIT;
END SP_ESTADO_ALERTA_CREATE;
/
