CREATE OR REPLACE PROCEDURE SP_INCIDENTE_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT INC_ID, INC_TIPO, INC_DESCRIPCION
    FROM PAR_INCIDENTE
    ORDER BY INC_ID;
END SP_INCIDENTE_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_INCIDENTE_GET_BY_ID (
    p_id IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT INC_ID, INC_TIPO, INC_DESCRIPCION
    FROM PAR_INCIDENTE
    WHERE INC_ID = p_id;
END SP_INCIDENTE_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_INCIDENTE_CREATE (
    p_INC_ID          IN VARCHAR2,
    p_INC_TIPO        IN VARCHAR2,
    p_INC_DESCRIPCION IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_INCIDENTE (INC_ID, INC_TIPO, INC_DESCRIPCION)
    VALUES (p_INC_ID, p_INC_TIPO, p_INC_DESCRIPCION);
    COMMIT;
END SP_INCIDENTE_CREATE;
/

CREATE OR REPLACE PROCEDURE SP_INCIDENTE_UPDATE (
    p_id              IN VARCHAR2,
    p_INC_TIPO        IN VARCHAR2,
    p_INC_DESCRIPCION IN VARCHAR2
) AS
BEGIN
    UPDATE PAR_INCIDENTE
    SET INC_TIPO        = p_INC_TIPO,
        INC_DESCRIPCION = p_INC_DESCRIPCION
    WHERE INC_ID = p_id;
    COMMIT;
END SP_INCIDENTE_UPDATE;
/

CREATE OR REPLACE PROCEDURE SP_INCIDENTE_DELETE (
    p_id      IN VARCHAR2,
    p_deleted OUT NUMBER
) AS
BEGIN
    DELETE FROM PAR_INCIDENTE WHERE INC_ID = p_id;
    p_deleted := SQL%ROWCOUNT;
    COMMIT;
END SP_INCIDENTE_DELETE;
/
