CREATE OR REPLACE PROCEDURE SP_MAQUINA_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT m.MAQ_ID, m.MAQ_CODIGO,
           m.TMA_ID, tm.TMA_TIPO, tm.TMA_DESCRIPCION,
           m.EMA_ID, em.EMA_ESTADO, em.EMA_DESCRIPCION,
           m.MAQ_FECHA_ULTIMA_RECARGA
    FROM PAR_MAQUINA m
    JOIN PAR_TIPO_MAQUINA   tm ON m.TMA_ID = tm.TMA_ID
    JOIN PAR_ESTADO_MAQUINA em ON m.EMA_ID = em.EMA_ID
    ORDER BY m.MAQ_ID;
END SP_MAQUINA_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_MAQUINA_GET_BY_ID (
    p_id IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT m.MAQ_ID, m.MAQ_CODIGO,
           m.TMA_ID, tm.TMA_TIPO, tm.TMA_DESCRIPCION,
           m.EMA_ID, em.EMA_ESTADO, em.EMA_DESCRIPCION,
           m.MAQ_FECHA_ULTIMA_RECARGA
    FROM PAR_MAQUINA m
    JOIN PAR_TIPO_MAQUINA   tm ON m.TMA_ID = tm.TMA_ID
    JOIN PAR_ESTADO_MAQUINA em ON m.EMA_ID = em.EMA_ID
    WHERE m.MAQ_ID = p_id;
END SP_MAQUINA_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_MAQUINA_CREATE (
    p_MAQ_ID                  IN VARCHAR2,
    p_MAQ_CODIGO              IN VARCHAR2,
    p_TMA_ID                  IN VARCHAR2,
    p_EMA_ID                  IN VARCHAR2,
    p_MAQ_FECHA_ULTIMA_RECARGA IN DATE
) AS
BEGIN
    INSERT INTO PAR_MAQUINA (MAQ_ID, MAQ_CODIGO, TMA_ID, EMA_ID, MAQ_FECHA_ULTIMA_RECARGA)
    VALUES (p_MAQ_ID, p_MAQ_CODIGO, p_TMA_ID, p_EMA_ID, p_MAQ_FECHA_ULTIMA_RECARGA);
    COMMIT;
END SP_MAQUINA_CREATE;
/

CREATE OR REPLACE PROCEDURE SP_MAQUINA_UPDATE (
    p_id                      IN VARCHAR2,
    p_MAQ_CODIGO              IN VARCHAR2,
    p_TMA_ID                  IN VARCHAR2,
    p_EMA_ID                  IN VARCHAR2,
    p_MAQ_FECHA_ULTIMA_RECARGA IN DATE
) AS
BEGIN
    UPDATE PAR_MAQUINA
    SET MAQ_CODIGO              = p_MAQ_CODIGO,
        TMA_ID                  = p_TMA_ID,
        EMA_ID                  = p_EMA_ID,
        MAQ_FECHA_ULTIMA_RECARGA = p_MAQ_FECHA_ULTIMA_RECARGA
    WHERE MAQ_ID = p_id;
    COMMIT;
END SP_MAQUINA_UPDATE;
/
