CREATE OR REPLACE PROCEDURE SP_NOTIFICACION_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT n.NOT_ID,
           n.TNO_ID, tn.TNO_TIPO, tn.TNO_DESCRIPCION,
           n.MEM_ID,
           n.NOT_ULTIMA_FECHA_ENVIO, n.NOT_PROXIMA_FECHA_ENVIO,
           n.NOT_EXITO,
           n.NOT_ASUNTO,
           n.NOT_CUERPO,
           v.VEH_PLACA,
           c.CLI_ID,
           c.CLI_PRIMER_NOMBRE, c.CLI_PRIMER_APELLIDO, c.CLI_CORREO
    FROM PAR_NOTIFICACION n
    JOIN PAR_TIPO_NOTIFICACION tn ON n.TNO_ID = tn.TNO_ID
    JOIN PAR_MEMBRESIA          m ON n.MEM_ID = m.MEM_ID
    JOIN PAR_VEHICULO           v ON v.VEH_ID = m.VEH_ID
    JOIN PAR_CLIENTE            c ON c.CLI_ID = v.CLI_ID
    ORDER BY n.NOT_ULTIMA_FECHA_ENVIO DESC, n.NOT_ID DESC;
END SP_NOTIFICACION_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_NOTIFICACION_GET_BY_ID (
    p_id IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT n.NOT_ID,
           n.TNO_ID, tn.TNO_TIPO, tn.TNO_DESCRIPCION,
           n.MEM_ID,
           n.NOT_ULTIMA_FECHA_ENVIO, n.NOT_PROXIMA_FECHA_ENVIO,
           n.NOT_EXITO,
           n.NOT_ASUNTO,
           n.NOT_CUERPO,
           v.VEH_PLACA,
           c.CLI_ID,
           c.CLI_PRIMER_NOMBRE, c.CLI_PRIMER_APELLIDO, c.CLI_CORREO
    FROM PAR_NOTIFICACION n
    JOIN PAR_TIPO_NOTIFICACION tn ON n.TNO_ID = tn.TNO_ID
    JOIN PAR_MEMBRESIA          m ON n.MEM_ID = m.MEM_ID
    JOIN PAR_VEHICULO           v ON v.VEH_ID = m.VEH_ID
    JOIN PAR_CLIENTE            c ON c.CLI_ID = v.CLI_ID
    WHERE n.NOT_ID = p_id;
END SP_NOTIFICACION_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_NOTIFICACION_CREATE (
    p_NOT_ID                  IN VARCHAR2,
    p_TNO_ID                  IN VARCHAR2,
    p_MEM_ID                  IN VARCHAR2,
    p_NOT_ULTIMA_FECHA_ENVIO  IN DATE,
    p_NOT_PROXIMA_FECHA_ENVIO IN DATE,
    p_NOT_EXITO               IN NUMBER,
    p_NOT_ASUNTO              IN VARCHAR2,
    p_NOT_CUERPO              IN CLOB
) AS
BEGIN
    INSERT INTO PAR_NOTIFICACION (
        NOT_ID, TNO_ID, MEM_ID,
        NOT_ULTIMA_FECHA_ENVIO, NOT_PROXIMA_FECHA_ENVIO, NOT_EXITO,
        NOT_ASUNTO, NOT_CUERPO
    )
    VALUES (
        p_NOT_ID, p_TNO_ID, p_MEM_ID,
        p_NOT_ULTIMA_FECHA_ENVIO, p_NOT_PROXIMA_FECHA_ENVIO, p_NOT_EXITO,
        p_NOT_ASUNTO, p_NOT_CUERPO
    );
    COMMIT;
END SP_NOTIFICACION_CREATE;
/
