CREATE OR REPLACE PROCEDURE SP_PAGO_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT p.PAG_ID, p.TPA_ID, tp.TPA_TIPO, tp.TPA_DESCRIPCION,
           p.PAG_MONTO_TOTAL, p.PAG_MONTO_RECIBIDO, p.PAG_VUELTO,
           p.PAG_FECHA_HORA
    FROM PAR_PAGO p
    JOIN PAR_TIPO_PAGO tp ON p.TPA_ID = tp.TPA_ID
    ORDER BY p.PAG_FECHA_HORA DESC;
END SP_PAGO_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_PAGO_GET_BY_ID (
    p_id IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT p.PAG_ID, p.TPA_ID, tp.TPA_TIPO, tp.TPA_DESCRIPCION,
           p.PAG_MONTO_TOTAL, p.PAG_MONTO_RECIBIDO, p.PAG_VUELTO,
           p.PAG_FECHA_HORA
    FROM PAR_PAGO p
    JOIN PAR_TIPO_PAGO tp ON p.TPA_ID = tp.TPA_ID
    WHERE p.PAG_ID = p_id;
END SP_PAGO_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_PAGO_CREATE (
    p_PAG_ID             IN VARCHAR2,
    p_TPA_ID             IN VARCHAR2,
    p_PAG_MONTO_TOTAL    IN NUMBER,
    p_PAG_MONTO_RECIBIDO IN NUMBER,
    p_PAG_VUELTO         IN NUMBER,
    p_PAG_FECHA_HORA     IN DATE
) AS
BEGIN
    INSERT INTO PAR_PAGO (PAG_ID, TPA_ID, PAG_MONTO_TOTAL, PAG_MONTO_RECIBIDO, PAG_VUELTO, PAG_FECHA_HORA)
    VALUES (p_PAG_ID, p_TPA_ID, p_PAG_MONTO_TOTAL, p_PAG_MONTO_RECIBIDO, p_PAG_VUELTO, p_PAG_FECHA_HORA);
    COMMIT;
END SP_PAGO_CREATE;
/
