CREATE OR REPLACE PROCEDURE SP_RECARGO_MAQUINA_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT r.RMA_ID, r.MAQ_ID, m.MAQ_CODIGO,
           r.RMA_MANTENIMIENTO_FECHA, r.RMA_DESCRIPCION
    FROM PAR_RECARGO_MAQUINA r
    JOIN PAR_MAQUINA m ON r.MAQ_ID = m.MAQ_ID
    ORDER BY r.RMA_ID;
END SP_RECARGO_MAQUINA_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_RECARGO_MAQUINA_GET_BY_ID (
    p_id IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT r.RMA_ID, r.MAQ_ID, m.MAQ_CODIGO,
           r.RMA_MANTENIMIENTO_FECHA, r.RMA_DESCRIPCION
    FROM PAR_RECARGO_MAQUINA r
    JOIN PAR_MAQUINA m ON r.MAQ_ID = m.MAQ_ID
    WHERE r.RMA_ID = p_id;
END SP_RECARGO_MAQUINA_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_RECARGO_MAQUINA_CREATE (
    p_RMA_ID                  IN VARCHAR2,
    p_MAQ_ID                  IN VARCHAR2,
    p_RMA_MANTENIMIENTO_FECHA IN DATE,
    p_RMA_DESCRIPCION         IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_RECARGO_MAQUINA (RMA_ID, MAQ_ID, RMA_MANTENIMIENTO_FECHA, RMA_DESCRIPCION)
    VALUES (p_RMA_ID, p_MAQ_ID, p_RMA_MANTENIMIENTO_FECHA, p_RMA_DESCRIPCION);
    COMMIT;
END SP_RECARGO_MAQUINA_CREATE;
/
