CREATE OR REPLACE PROCEDURE SP_REG_MANTENIMIENTO_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT r.REM_ID, r.MAQ_ID, m.MAQ_CODIGO,
           r.REM_MANTENIMIENTO_FECHA, r.REM_DESCRIPCION
    FROM PAR_REGISTRO_MANTENIMIENTO r
    JOIN PAR_MAQUINA m ON r.MAQ_ID = m.MAQ_ID
    ORDER BY r.REM_ID;
END SP_REG_MANTENIMIENTO_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_REG_MANTENIMIENTO_GET_BY_ID (
    p_id IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT r.REM_ID, r.MAQ_ID, m.MAQ_CODIGO,
           r.REM_MANTENIMIENTO_FECHA, r.REM_DESCRIPCION
    FROM PAR_REGISTRO_MANTENIMIENTO r
    JOIN PAR_MAQUINA m ON r.MAQ_ID = m.MAQ_ID
    WHERE r.REM_ID = p_id;
END SP_REG_MANTENIMIENTO_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_REG_MANTENIMIENTO_CREATE (
    p_REM_ID                  IN VARCHAR2,
    p_MAQ_ID                  IN VARCHAR2,
    p_REM_MANTENIMIENTO_FECHA IN DATE,
    p_REM_DESCRIPCION         IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_REGISTRO_MANTENIMIENTO (REM_ID, MAQ_ID, REM_MANTENIMIENTO_FECHA, REM_DESCRIPCION)
    VALUES (p_REM_ID, p_MAQ_ID, p_REM_MANTENIMIENTO_FECHA, p_REM_DESCRIPCION);
    COMMIT;
END SP_REG_MANTENIMIENTO_CREATE;
/
