CREATE OR REPLACE PROCEDURE SP_REG_MANTENIMIENTO_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT r.REM_ID, r.MAQ_ID, m.MAQ_CODIGO,
           r.REM_MANTENIMIENTO_FECHA, r.REM_DESCRIPCION,
           r.REM_TIPO_MOVIMIENTO, r.REM_ESTADO_RESULTANTE_EMA_ID,
           em.EMA_ESTADO AS REM_ESTADO_RESULTANTE
    FROM PAR_REGISTRO_MANTENIMIENTO r
    JOIN PAR_MAQUINA m ON r.MAQ_ID = m.MAQ_ID
    LEFT JOIN PAR_ESTADO_MAQUINA em ON em.EMA_ID = r.REM_ESTADO_RESULTANTE_EMA_ID
    ORDER BY r.REM_ID;
END SP_REG_MANTENIMIENTO_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_REG_MANTENIMIENTO_GET_BY_ID (
    p_id IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT r.REM_ID, r.MAQ_ID, m.MAQ_CODIGO,
           r.REM_MANTENIMIENTO_FECHA, r.REM_DESCRIPCION,
           r.REM_TIPO_MOVIMIENTO, r.REM_ESTADO_RESULTANTE_EMA_ID,
           em.EMA_ESTADO AS REM_ESTADO_RESULTANTE
    FROM PAR_REGISTRO_MANTENIMIENTO r
    JOIN PAR_MAQUINA m ON r.MAQ_ID = m.MAQ_ID
    LEFT JOIN PAR_ESTADO_MAQUINA em ON em.EMA_ID = r.REM_ESTADO_RESULTANTE_EMA_ID
    WHERE r.REM_ID = p_id;
END SP_REG_MANTENIMIENTO_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_REG_MANTENIMIENTO_CREATE (
    p_REM_ID                  IN VARCHAR2,
    p_MAQ_ID                  IN VARCHAR2,
    p_REM_MANTENIMIENTO_FECHA IN DATE,
    p_REM_DESCRIPCION         IN VARCHAR2,
    p_REM_TIPO_MOVIMIENTO     IN VARCHAR2,
    p_REM_ESTADO_RESULTANTE_EMA_ID IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_REGISTRO_MANTENIMIENTO (
      REM_ID, MAQ_ID, REM_MANTENIMIENTO_FECHA, REM_DESCRIPCION, REM_TIPO_MOVIMIENTO, REM_ESTADO_RESULTANTE_EMA_ID
    )
    VALUES (
      p_REM_ID, p_MAQ_ID, p_REM_MANTENIMIENTO_FECHA, p_REM_DESCRIPCION, p_REM_TIPO_MOVIMIENTO, p_REM_ESTADO_RESULTANTE_EMA_ID
    );
    COMMIT;
END SP_REG_MANTENIMIENTO_CREATE;
/
