CREATE OR REPLACE PROCEDURE SP_REGISTRO_MOV_MEM_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT RMM_ID, RMM_FECHA_HORA_ENTRADA, RMM_FECHA_HORA_SALIDA, MEM_ID
    FROM PAR_REGISTRO_MOVIMIENTO_MEMBRESIA;
END SP_REGISTRO_MOV_MEM_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_REGISTRO_MOV_MEM_GET_BY_ID (
    p_id IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT RMM_ID, RMM_FECHA_HORA_ENTRADA, RMM_FECHA_HORA_SALIDA, MEM_ID
    FROM PAR_REGISTRO_MOVIMIENTO_MEMBRESIA
    WHERE RMM_ID = p_id;
END SP_REGISTRO_MOV_MEM_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_REGISTRO_MOV_MEM_CREATE (
    p_RMM_ID IN NUMBER,
    p_RMM_FECHA_HORA_ENTRADA IN TIMESTAMP,
    p_RMM_FECHA_HORA_SALIDA IN TIMESTAMP,
    p_MEM_ID IN NUMBER
) AS
BEGIN
    INSERT INTO PAR_REGISTRO_MOVIMIENTO_MEMBRESIA (RMM_ID, RMM_FECHA_HORA_ENTRADA, RMM_FECHA_HORA_SALIDA, MEM_ID)
    VALUES (p_RMM_ID, p_RMM_FECHA_HORA_ENTRADA, p_RMM_FECHA_HORA_SALIDA, p_MEM_ID);
    COMMIT;
END SP_REGISTRO_MOV_MEM_CREATE;
/
