CREATE OR REPLACE PROCEDURE SP_REGISTRO_MOV_MEM_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT r.RMM_ID, r.RMM_FECHA_HORA_ENTRADA, r.RMM_FECHA_HORA_SALIDA, r.MEM_ID
        FROM PAR_REGISTRO_MOVIMIENTO_MEMBRESIA r
        ORDER BY r.RMM_FECHA_HORA_ENTRADA DESC;
END SP_REGISTRO_MOV_MEM_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_REGISTRO_MOV_MEM_GET_BY_ID (
    p_id     IN  VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT RMM_ID, RMM_FECHA_HORA_ENTRADA, RMM_FECHA_HORA_SALIDA, MEM_ID
        FROM PAR_REGISTRO_MOVIMIENTO_MEMBRESIA
        WHERE RMM_ID = p_id;
END SP_REGISTRO_MOV_MEM_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_REGISTRO_MOV_MEM_CREATE (
    p_RMM_ID                IN VARCHAR2,
    p_RMM_FECHA_HORA_ENTRADA IN DATE,
    p_RMM_FECHA_HORA_SALIDA  IN DATE,
    p_MEM_ID                IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_REGISTRO_MOVIMIENTO_MEMBRESIA (
        RMM_ID, RMM_FECHA_HORA_ENTRADA, RMM_FECHA_HORA_SALIDA, MEM_ID
    ) VALUES (
        p_RMM_ID, p_RMM_FECHA_HORA_ENTRADA, p_RMM_FECHA_HORA_SALIDA, p_MEM_ID
    );
    COMMIT;
END SP_REGISTRO_MOV_MEM_CREATE;
/
