CREATE OR REPLACE PROCEDURE SP_SALDO_DISP_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT SDI_ID, SDI_TIPO, SDI_VALOR
    FROM PAR_SALDO_DISPONIBLE
    ORDER BY SDI_ID;
END SP_SALDO_DISP_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_SALDO_DISP_GET_BY_ID (
    p_id IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT SDI_ID, SDI_TIPO, SDI_VALOR
    FROM PAR_SALDO_DISPONIBLE
    WHERE SDI_ID = p_id;
END SP_SALDO_DISP_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_SALDO_DISP_CREATE (
    p_SDI_ID    IN VARCHAR2,
    p_SDI_TIPO  IN VARCHAR2,
    p_SDI_VALOR IN NUMBER
) AS
BEGIN
    INSERT INTO PAR_SALDO_DISPONIBLE (SDI_ID, SDI_TIPO, SDI_VALOR)
    VALUES (p_SDI_ID, p_SDI_TIPO, p_SDI_VALOR);
    COMMIT;
END SP_SALDO_DISP_CREATE;
/

CREATE OR REPLACE PROCEDURE SP_SALDO_DISP_UPDATE (
    p_id        IN VARCHAR2,
    p_SDI_TIPO  IN VARCHAR2,
    p_SDI_VALOR IN NUMBER
) AS
BEGIN
    UPDATE PAR_SALDO_DISPONIBLE
    SET SDI_TIPO  = p_SDI_TIPO,
        SDI_VALOR = p_SDI_VALOR
    WHERE SDI_ID = p_id;
    COMMIT;
END SP_SALDO_DISP_UPDATE;
/
