CREATE OR REPLACE PROCEDURE SP_TARIFA_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT TAR_ID, TAR_TIPO, TAR_PRECIO
        FROM PAR_TARIFA
        ORDER BY TAR_ID;
END SP_TARIFA_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_TARIFA_GET_BY_ID (
    p_id     IN  VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT TAR_ID, TAR_TIPO, TAR_PRECIO
        FROM PAR_TARIFA
        WHERE TAR_ID = p_id;
END SP_TARIFA_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_TARIFA_CREATE (
    p_TAR_ID    IN VARCHAR2,
    p_TAR_TIPO  IN VARCHAR2,
    p_TAR_PRECIO IN NUMBER
) AS
BEGIN
    INSERT INTO PAR_TARIFA (TAR_ID, TAR_TIPO, TAR_PRECIO)
    VALUES (p_TAR_ID, p_TAR_TIPO, p_TAR_PRECIO);
    COMMIT;
END SP_TARIFA_CREATE;
/

CREATE OR REPLACE PROCEDURE SP_TARIFA_UPDATE (
    p_id        IN VARCHAR2,
    p_TAR_TIPO  IN VARCHAR2,
    p_TAR_PRECIO IN NUMBER
) AS
BEGIN
    UPDATE PAR_TARIFA
    SET TAR_TIPO  = p_TAR_TIPO,
        TAR_PRECIO = p_TAR_PRECIO
    WHERE TAR_ID = p_id;
    COMMIT;
END SP_TARIFA_UPDATE;
/

CREATE OR REPLACE PROCEDURE SP_TARIFA_DELETE (
    p_id      IN  VARCHAR2,
    p_deleted OUT NUMBER
) AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM PAR_COBRO WHERE TAR_ID = p_id;
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar: existen cobros con esta tarifa');
    END IF;
    DELETE FROM PAR_TARIFA WHERE TAR_ID = p_id;
    p_deleted := SQL%ROWCOUNT;
    COMMIT;
END SP_TARIFA_DELETE;
/
