CREATE OR REPLACE PROCEDURE SP_TICKET_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT t.TIC_ID, t.TIC_CODIGO,
           t.VEH_ID, v.VEH_PLACA, v.VEH_MODELO, v.VEH_COLOR,
           t.TIC_FECHA_HORA_ENTRADA, t.TIC_FECHA_HORA_SALIDA,
           t.ETI_ID, e.ETI_ESTADO,
           t.COB_ID
    FROM PAR_TICKET t
    JOIN PAR_VEHICULO      v ON t.VEH_ID = v.VEH_ID
    JOIN PAR_ESTADO_TICKET e ON t.ETI_ID = e.ETI_ID
    ORDER BY t.TIC_FECHA_HORA_ENTRADA DESC;
END SP_TICKET_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_TICKET_GET_BY_ID (
    p_id IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT t.TIC_ID, t.TIC_CODIGO,
           t.VEH_ID, v.VEH_PLACA, v.VEH_MODELO, v.VEH_COLOR,
           t.TIC_FECHA_HORA_ENTRADA, t.TIC_FECHA_HORA_SALIDA,
           t.ETI_ID, e.ETI_ESTADO,
           t.COB_ID
    FROM PAR_TICKET t
    JOIN PAR_VEHICULO      v ON t.VEH_ID = v.VEH_ID
    JOIN PAR_ESTADO_TICKET e ON t.ETI_ID = e.ETI_ID
    WHERE t.TIC_ID = p_id;
END SP_TICKET_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_TICKET_CREATE (
    p_TIC_ID                 IN VARCHAR2,
    p_TIC_CODIGO             IN VARCHAR2,
    p_VEH_ID                 IN VARCHAR2,
    p_TIC_FECHA_HORA_ENTRADA IN DATE,
    p_TIC_FECHA_HORA_SALIDA  IN DATE,
    p_ETI_ID                 IN VARCHAR2,
    p_COB_ID                 IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_TICKET (
        TIC_ID, TIC_CODIGO, VEH_ID,
        TIC_FECHA_HORA_ENTRADA, TIC_FECHA_HORA_SALIDA,
        ETI_ID, COB_ID
    )
    VALUES (
        p_TIC_ID, p_TIC_CODIGO, p_VEH_ID,
        p_TIC_FECHA_HORA_ENTRADA, p_TIC_FECHA_HORA_SALIDA,
        p_ETI_ID, p_COB_ID
    );
    COMMIT;
END SP_TICKET_CREATE;
/
