CREATE OR REPLACE PROCEDURE SP_TIPO_VEHICULO_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT TVE_ID, TVE_TIPO, TVE_MARCA, TVE_DESCRIPCION
    FROM PAR_TIPO_VEHICULO;
END SP_TIPO_VEHICULO_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_VEHICULO_GET_BY_ID (
    p_id IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT TVE_ID, TVE_TIPO, TVE_MARCA, TVE_DESCRIPCION
    FROM PAR_TIPO_VEHICULO
    WHERE TVE_ID = p_id;
END SP_TIPO_VEHICULO_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_VEHICULO_CREATE (
    p_TVE_ID IN NUMBER,
    p_TVE_TIPO IN VARCHAR2,
    p_TVE_MARCA IN VARCHAR2,
    p_TVE_DESCRIPCION IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_TIPO_VEHICULO (TVE_ID, TVE_TIPO, TVE_MARCA, TVE_DESCRIPCION)
    VALUES (p_TVE_ID, p_TVE_TIPO, p_TVE_MARCA, p_TVE_DESCRIPCION);
    COMMIT;
END SP_TIPO_VEHICULO_CREATE;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_VEHICULO_UPDATE (
    p_id IN NUMBER,
    p_TVE_TIPO IN VARCHAR2,
    p_TVE_MARCA IN VARCHAR2,
    p_TVE_DESCRIPCION IN VARCHAR2
) AS
BEGIN
    UPDATE PAR_TIPO_VEHICULO
    SET TVE_TIPO = p_TVE_TIPO,
        TVE_MARCA = p_TVE_MARCA,
        TVE_DESCRIPCION = p_TVE_DESCRIPCION
    WHERE TVE_ID = p_id;
    COMMIT;
END SP_TIPO_VEHICULO_UPDATE;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_VEHICULO_DELETE (
    p_id IN NUMBER
) AS
BEGIN
    DELETE FROM PAR_TIPO_VEHICULO WHERE TVE_ID = p_id;
    COMMIT;
END SP_TIPO_VEHICULO_DELETE;
/
