CREATE OR REPLACE PROCEDURE SP_TIPO_PAGO_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT TPA_ID, TPA_TIPO, TPA_DESCRIPCION
    FROM PAR_TIPO_PAGO
    ORDER BY TPA_ID;
END SP_TIPO_PAGO_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_PAGO_GET_BY_ID (
    p_id IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT TPA_ID, TPA_TIPO, TPA_DESCRIPCION
    FROM PAR_TIPO_PAGO
    WHERE TPA_ID = p_id;
END SP_TIPO_PAGO_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_PAGO_CREATE (
    p_TPA_ID          IN VARCHAR2,
    p_TPA_TIPO        IN VARCHAR2,
    p_TPA_DESCRIPCION IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_TIPO_PAGO (TPA_ID, TPA_TIPO, TPA_DESCRIPCION)
    VALUES (p_TPA_ID, p_TPA_TIPO, p_TPA_DESCRIPCION);
    COMMIT;
END SP_TIPO_PAGO_CREATE;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_PAGO_UPDATE (
    p_id              IN VARCHAR2,
    p_TPA_TIPO        IN VARCHAR2,
    p_TPA_DESCRIPCION IN VARCHAR2
) AS
BEGIN
    UPDATE PAR_TIPO_PAGO
    SET TPA_TIPO        = p_TPA_TIPO,
        TPA_DESCRIPCION = p_TPA_DESCRIPCION
    WHERE TPA_ID = p_id;
    COMMIT;
END SP_TIPO_PAGO_UPDATE;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_PAGO_DELETE (
    p_id      IN VARCHAR2,
    p_deleted OUT NUMBER
) AS
BEGIN
    DELETE FROM PAR_TIPO_PAGO WHERE TPA_ID = p_id;
    p_deleted := SQL%ROWCOUNT;
    COMMIT;
END SP_TIPO_PAGO_DELETE;
/
