CREATE OR REPLACE PROCEDURE SP_TIPO_MEMBRESIA_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT TME_ID, TME_TIPO, TME_DESCRIPCION, TME_DURACION, TME_PRECIO
    FROM PAR_TIPO_MEMBRESIA;
END SP_TIPO_MEMBRESIA_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_MEMBRESIA_GET_BY_ID (
    p_id IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT TME_ID, TME_TIPO, TME_DESCRIPCION, TME_DURACION, TME_PRECIO
    FROM PAR_TIPO_MEMBRESIA
    WHERE TME_ID = p_id;
END SP_TIPO_MEMBRESIA_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_MEMBRESIA_CREATE (
    p_TME_ID IN NUMBER,
    p_TME_TIPO IN VARCHAR2,
    p_TME_DESCRIPCION IN VARCHAR2,
    p_TME_DURACION IN NUMBER,
    p_TME_PRECIO IN NUMBER
) AS
BEGIN
    INSERT INTO PAR_TIPO_MEMBRESIA (TME_ID, TME_TIPO, TME_DESCRIPCION, TME_DURACION, TME_PRECIO)
    VALUES (p_TME_ID, p_TME_TIPO, p_TME_DESCRIPCION, p_TME_DURACION, p_TME_PRECIO);
    COMMIT;
END SP_TIPO_MEMBRESIA_CREATE;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_MEMBRESIA_UPDATE (
    p_id IN NUMBER,
    p_TME_TIPO IN VARCHAR2,
    p_TME_DESCRIPCION IN VARCHAR2,
    p_TME_DURACION IN NUMBER,
    p_TME_PRECIO IN NUMBER
) AS
BEGIN
    UPDATE PAR_TIPO_MEMBRESIA
    SET TME_TIPO = p_TME_TIPO,
        TME_DESCRIPCION = p_TME_DESCRIPCION,
        TME_DURACION = p_TME_DURACION,
        TME_PRECIO = p_TME_PRECIO
    WHERE TME_ID = p_id;
    COMMIT;
END SP_TIPO_MEMBRESIA_UPDATE;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_MEMBRESIA_DELETE (
    p_id IN NUMBER
) AS
BEGIN
    DELETE FROM PAR_TIPO_MEMBRESIA WHERE TME_ID = p_id;
    COMMIT;
END SP_TIPO_MEMBRESIA_DELETE;
/
