CREATE OR REPLACE PROCEDURE SP_TIPO_ALERTA_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT TAL_ID, TAL_TIPO, TAL_DESCRIPCION
    FROM PAR_TIPO_ALERTA;
END SP_TIPO_ALERTA_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_ALERTA_GET_BY_ID (
    p_id IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT TAL_ID, TAL_TIPO, TAL_DESCRIPCION
    FROM PAR_TIPO_ALERTA
    WHERE TAL_ID = p_id;
END SP_TIPO_ALERTA_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_ALERTA_CREATE (
    p_TAL_ID IN NUMBER,
    p_TAL_TIPO IN VARCHAR2,
    p_TAL_DESCRIPCION IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_TIPO_ALERTA (TAL_ID, TAL_TIPO, TAL_DESCRIPCION)
    VALUES (p_TAL_ID, p_TAL_TIPO, p_TAL_DESCRIPCION);
    COMMIT;
END SP_TIPO_ALERTA_CREATE;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_ALERTA_UPDATE (
    p_id IN NUMBER,
    p_TAL_TIPO IN VARCHAR2,
    p_TAL_DESCRIPCION IN VARCHAR2
) AS
BEGIN
    UPDATE PAR_TIPO_ALERTA
    SET TAL_TIPO = p_TAL_TIPO,
        TAL_DESCRIPCION = p_TAL_DESCRIPCION
    WHERE TAL_ID = p_id;
    COMMIT;
END SP_TIPO_ALERTA_UPDATE;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_ALERTA_DELETE (
    p_id IN NUMBER
) AS
BEGIN
    DELETE FROM PAR_TIPO_ALERTA WHERE TAL_ID = p_id;
    COMMIT;
END SP_TIPO_ALERTA_DELETE;
/
