CREATE OR REPLACE PROCEDURE SP_TIPO_VEHICULO_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT TVE_ID, TVE_TIPO, TVE_DESCRIPCION
        FROM PAR_TIPO_VEHICULO
        ORDER BY TVE_ID;
END SP_TIPO_VEHICULO_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_VEHICULO_GET_BY_ID (
    p_id     IN  VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT TVE_ID, TVE_TIPO, TVE_DESCRIPCION
        FROM PAR_TIPO_VEHICULO
        WHERE TVE_ID = p_id;
END SP_TIPO_VEHICULO_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_VEHICULO_CREATE (
    p_TVE_ID          IN VARCHAR2,
    p_TVE_TIPO        IN VARCHAR2,
    p_TVE_DESCRIPCION IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_TIPO_VEHICULO (TVE_ID, TVE_TIPO, TVE_DESCRIPCION)
    VALUES (p_TVE_ID, p_TVE_TIPO, p_TVE_DESCRIPCION);
    COMMIT;
END SP_TIPO_VEHICULO_CREATE;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_VEHICULO_UPDATE (
    p_id              IN VARCHAR2,
    p_TVE_TIPO        IN VARCHAR2,
    p_TVE_DESCRIPCION IN VARCHAR2
) AS
BEGIN
    UPDATE PAR_TIPO_VEHICULO
    SET TVE_TIPO        = p_TVE_TIPO,
        TVE_DESCRIPCION = p_TVE_DESCRIPCION
    WHERE TVE_ID = p_id;
    COMMIT;
END SP_TIPO_VEHICULO_UPDATE;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_VEHICULO_DELETE (
    p_id      IN  VARCHAR2,
    p_deleted OUT NUMBER
) AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM PAR_MODELO_VEHICULO WHERE TVE_ID = p_id;
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar: existen modelos con este tipo');
    END IF;
    DELETE FROM PAR_TIPO_VEHICULO WHERE TVE_ID = p_id;
    p_deleted := SQL%ROWCOUNT;
    COMMIT;
END SP_TIPO_VEHICULO_DELETE;
/
