CREATE OR REPLACE PROCEDURE SP_TIPO_NOTIF_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT TNO_ID, TNO_TIPO, TNO_DESCRIPCION
    FROM PAR_TIPO_NOTIFICACION
    ORDER BY TNO_ID;
END SP_TIPO_NOTIF_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_NOTIF_GET_BY_ID (
    p_id IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT TNO_ID, TNO_TIPO, TNO_DESCRIPCION
    FROM PAR_TIPO_NOTIFICACION
    WHERE TNO_ID = p_id;
END SP_TIPO_NOTIF_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_NOTIF_CREATE (
    p_TNO_ID          IN VARCHAR2,
    p_TNO_TIPO        IN VARCHAR2,
    p_TNO_DESCRIPCION IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_TIPO_NOTIFICACION (TNO_ID, TNO_TIPO, TNO_DESCRIPCION)
    VALUES (p_TNO_ID, p_TNO_TIPO, p_TNO_DESCRIPCION);
    COMMIT;
END SP_TIPO_NOTIF_CREATE;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_NOTIF_UPDATE (
    p_id              IN VARCHAR2,
    p_TNO_TIPO        IN VARCHAR2,
    p_TNO_DESCRIPCION IN VARCHAR2
) AS
BEGIN
    UPDATE PAR_TIPO_NOTIFICACION
    SET TNO_TIPO        = p_TNO_TIPO,
        TNO_DESCRIPCION = p_TNO_DESCRIPCION
    WHERE TNO_ID = p_id;
    COMMIT;
END SP_TIPO_NOTIF_UPDATE;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_NOTIF_DELETE (
    p_id      IN VARCHAR2,
    p_deleted OUT NUMBER
) AS
BEGIN
    DELETE FROM PAR_TIPO_NOTIFICACION WHERE TNO_ID = p_id;
    p_deleted := SQL%ROWCOUNT;
    COMMIT;
END SP_TIPO_NOTIF_DELETE;
/
