CREATE OR REPLACE PROCEDURE SP_TIPO_MEMBRESIA_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT TME_ID, TME_TIPO, TME_DESCRIPCION, TME_DURACION, TME_PRECIO
        FROM PAR_TIPO_MEMBRESIA
        ORDER BY TME_ID;
END SP_TIPO_MEMBRESIA_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_MEMBRESIA_GET_BY_ID (
    p_id     IN  VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT TME_ID, TME_TIPO, TME_DESCRIPCION, TME_DURACION, TME_PRECIO
        FROM PAR_TIPO_MEMBRESIA
        WHERE TME_ID = p_id;
END SP_TIPO_MEMBRESIA_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_MEMBRESIA_CREATE (
    p_TME_ID          IN VARCHAR2,
    p_TME_TIPO        IN VARCHAR2,
    p_TME_DESCRIPCION IN VARCHAR2,
    p_TME_DURACION    IN NUMBER,
    p_TME_PRECIO      IN NUMBER
) AS
BEGIN
    INSERT INTO PAR_TIPO_MEMBRESIA (TME_ID, TME_TIPO, TME_DESCRIPCION, TME_DURACION, TME_PRECIO)
    VALUES (p_TME_ID, p_TME_TIPO, p_TME_DESCRIPCION, p_TME_DURACION, p_TME_PRECIO);
    COMMIT;
END SP_TIPO_MEMBRESIA_CREATE;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_MEMBRESIA_UPDATE (
    p_id              IN VARCHAR2,
    p_TME_TIPO        IN VARCHAR2,
    p_TME_DESCRIPCION IN VARCHAR2,
    p_TME_DURACION    IN NUMBER,
    p_TME_PRECIO      IN NUMBER
) AS
BEGIN
    UPDATE PAR_TIPO_MEMBRESIA
    SET TME_TIPO        = p_TME_TIPO,
        TME_DESCRIPCION = p_TME_DESCRIPCION,
        TME_DURACION    = p_TME_DURACION,
        TME_PRECIO      = p_TME_PRECIO
    WHERE TME_ID = p_id;
    COMMIT;
END SP_TIPO_MEMBRESIA_UPDATE;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_MEMBRESIA_DELETE (
    p_id      IN  VARCHAR2,
    p_deleted OUT NUMBER
) AS
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM PAR_MEMBRESIA WHERE TME_ID = p_id;
    IF v_count > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'No se puede eliminar: existen membresías con este tipo');
    END IF;
    DELETE FROM PAR_TIPO_MEMBRESIA WHERE TME_ID = p_id;
    p_deleted := SQL%ROWCOUNT;
    COMMIT;
END SP_TIPO_MEMBRESIA_DELETE;
/
