CREATE OR REPLACE PROCEDURE SP_TIPO_COBRO_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT TCO_ID, TCO_TIPO, TCO_DESCRIPCION
    FROM PAR_TIPO_COBRO;
END SP_TIPO_COBRO_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_COBRO_GET_BY_ID (
    p_id IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
    SELECT TCO_ID, TCO_TIPO, TCO_DESCRIPCION
    FROM PAR_TIPO_COBRO
    WHERE TCO_ID = p_id;
END SP_TIPO_COBRO_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_COBRO_CREATE (
    p_TCO_ID IN NUMBER,
    p_TCO_TIPO IN VARCHAR2,
    p_TCO_DESCRIPCION IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_TIPO_COBRO (TCO_ID, TCO_TIPO, TCO_DESCRIPCION)
    VALUES (p_TCO_ID, p_TCO_TIPO, p_TCO_DESCRIPCION);
    COMMIT;
END SP_TIPO_COBRO_CREATE;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_COBRO_UPDATE (
    p_id IN NUMBER,
    p_TCO_TIPO IN VARCHAR2,
    p_TCO_DESCRIPCION IN VARCHAR2
) AS
BEGIN
    UPDATE PAR_TIPO_COBRO
    SET TCO_TIPO = p_TCO_TIPO,
        TCO_DESCRIPCION = p_TCO_DESCRIPCION
    WHERE TCO_ID = p_id;
    COMMIT;
END SP_TIPO_COBRO_UPDATE;
/

CREATE OR REPLACE PROCEDURE SP_TIPO_COBRO_DELETE (
    p_id IN NUMBER
) AS
BEGIN
    DELETE FROM PAR_TIPO_COBRO WHERE TCO_ID = p_id;
    COMMIT;
END SP_TIPO_COBRO_DELETE;
/
