CREATE OR REPLACE PROCEDURE SP_VEHICULO_GET_ALL (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT v.VEH_ID, v.VEH_PLACA, v.VEH_MODELO, v.VEH_COLOR,
               v.TVE_ID, tv.TVE_TIPO, v.CLI_ID
        FROM PAR_VEHICULO v
        LEFT JOIN PAR_TIPO_VEHICULO tv ON v.TVE_ID = tv.TVE_ID
        ORDER BY v.VEH_ID;
END SP_VEHICULO_GET_ALL;
/

CREATE OR REPLACE PROCEDURE SP_VEHICULO_GET_BY_ID (
    p_id     IN  VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT v.VEH_ID, v.VEH_PLACA, v.VEH_MODELO, v.VEH_COLOR,
               v.TVE_ID, tv.TVE_TIPO, v.CLI_ID
        FROM PAR_VEHICULO v
        LEFT JOIN PAR_TIPO_VEHICULO tv ON v.TVE_ID = tv.TVE_ID
        WHERE v.VEH_ID = p_id;
END SP_VEHICULO_GET_BY_ID;
/

CREATE OR REPLACE PROCEDURE SP_VEHICULO_CREATE (
    p_VEH_ID    IN VARCHAR2,
    p_VEH_PLACA IN VARCHAR2,
    p_VEH_MODELO IN VARCHAR2,
    p_VEH_COLOR IN VARCHAR2,
    p_TVE_ID    IN VARCHAR2,
    p_CLI_ID    IN VARCHAR2
) AS
BEGIN
    INSERT INTO PAR_VEHICULO (VEH_ID, VEH_PLACA, VEH_MODELO, VEH_COLOR, TVE_ID, CLI_ID)
    VALUES (p_VEH_ID, p_VEH_PLACA, p_VEH_MODELO, p_VEH_COLOR, p_TVE_ID, p_CLI_ID);
    COMMIT;
END SP_VEHICULO_CREATE;
/

CREATE OR REPLACE PROCEDURE SP_VEHICULO_UPDATE (
    p_id        IN VARCHAR2,
    p_VEH_PLACA IN VARCHAR2,
    p_VEH_MODELO IN VARCHAR2,
    p_VEH_COLOR IN VARCHAR2,
    p_TVE_ID    IN VARCHAR2,
    p_CLI_ID    IN VARCHAR2
) AS
BEGIN
    UPDATE PAR_VEHICULO
    SET VEH_PLACA  = p_VEH_PLACA,
        VEH_MODELO = p_VEH_MODELO,
        VEH_COLOR  = p_VEH_COLOR,
        TVE_ID     = p_TVE_ID,
        CLI_ID     = p_CLI_ID
    WHERE VEH_ID = p_id;
    COMMIT;
END SP_VEHICULO_UPDATE;
/
