-- Script DDL PAR (Gestor de Parqueo)

CREATE TABLE PAR_TIPO_VEHICULO (
    TVE_ID          NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    TVE_TIPO        VARCHAR2(30)   NOT NULL,
    TVE_DESCRIPCION VARCHAR2(500),
    CONSTRAINT PK_PAR_TIPO_VEHICULO PRIMARY KEY (TVE_ID),
    CONSTRAINT UK_PAR_TIPO_VEHICULO_TIPO UNIQUE (TVE_TIPO)
);

CREATE TABLE PAR_MARCA_VEHICULO (
    MAR_ID          NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    MAR_NOMBRE      VARCHAR2(100) NOT NULL,
    MAR_DESCRIPCION VARCHAR2(500),
    CONSTRAINT PK_PAR_MARCA_VEHICULO PRIMARY KEY (MAR_ID),
    CONSTRAINT UK_PAR_MARCA_VEHICULO_NOMBRE UNIQUE (MAR_NOMBRE)
);

CREATE TABLE PAR_COLOR_VEHICULO (
    COL_ID          NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    COL_NOMBRE      VARCHAR2(50) NOT NULL,
    COL_DESCRIPCION VARCHAR2(500),
    CONSTRAINT PK_PAR_COLOR_VEHICULO PRIMARY KEY (COL_ID),
    CONSTRAINT UK_PAR_COLOR_VEHICULO_NOMBRE UNIQUE (COL_NOMBRE)
);

CREATE TABLE PAR_MODELO_VEHICULO (
    MOD_ID          NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    MOD_NOMBRE      VARCHAR2(100) NOT NULL,
    MAR_ID          NUMBER(10) NOT NULL,
    TVE_ID          NUMBER(10) NOT NULL,
    MOD_DESCRIPCION VARCHAR2(500),
    CONSTRAINT PK_PAR_MODELO_VEHICULO PRIMARY KEY (MOD_ID),
    CONSTRAINT UK_PAR_MODELO_VEHICULO UNIQUE (MAR_ID, MOD_NOMBRE),
    CONSTRAINT FK_PAR_MODELO_VEHICULO_MARCA FOREIGN KEY (MAR_ID) REFERENCES PAR_MARCA_VEHICULO(MAR_ID),
    CONSTRAINT FK_PAR_MODELO_VEHICULO_TIPO FOREIGN KEY (TVE_ID) REFERENCES PAR_TIPO_VEHICULO(TVE_ID)
);

CREATE TABLE PAR_CLIENTE (
    CLI_ID              NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    CLI_PRIMER_NOMBRE   VARCHAR2(100) NOT NULL,
    CLI_SEGUNDO_NOMBRE  VARCHAR2(100),
    CLI_PRIMER_APELLIDO VARCHAR2(100) NOT NULL,
    CLI_SEGUNDO_APELLIDO VARCHAR2(100),
    CLI_DPI             VARCHAR2(20)  NOT NULL,
    CLI_NIT             VARCHAR2(20),
    CLI_CORREO          VARCHAR2(100),
    CLI_TELEFONO        VARCHAR2(20),
    CLI_ZONA            VARCHAR2(50),
    CLI_CALLE           VARCHAR2(100),
    CLI_NUMERO          VARCHAR2(20),
    CLI_COLONIA         VARCHAR2(100),
    CLI_CIUDAD          VARCHAR2(100),
    CLI_CODIGO_POSTAL   VARCHAR2(20),
    CLI_ACTIVO          NUMBER(1)     NOT NULL,
    CLI_FECHA_REGISTRO  DATE          NOT NULL,
    CONSTRAINT PK_PAR_CLIENTE PRIMARY KEY (CLI_ID)
);

CREATE TABLE PAR_VEHICULO (
    VEH_ID     NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    VEH_PLACA  VARCHAR2(7)   NOT NULL,
    MOD_ID     NUMBER(10) NOT NULL,
    COL_ID     NUMBER(10),
    CLI_ID     NUMBER(10),
    CONSTRAINT PK_PAR_VEHICULO PRIMARY KEY (VEH_ID),
    CONSTRAINT UK_PAR_VEHICULO_PLACA UNIQUE (VEH_PLACA),
    CONSTRAINT FK_PAR_VEHICULO_MODELO  FOREIGN KEY (MOD_ID) REFERENCES PAR_MODELO_VEHICULO(MOD_ID),
    CONSTRAINT FK_PAR_VEHICULO_COLOR   FOREIGN KEY (COL_ID) REFERENCES PAR_COLOR_VEHICULO(COL_ID),
    CONSTRAINT FK_PAR_VEHICULO_CLIENTE FOREIGN KEY (CLI_ID) REFERENCES PAR_CLIENTE(CLI_ID)
);

CREATE TABLE PAR_ESTADO_TICKET (
    ETI_ID     NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    ETI_ESTADO VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_PAR_ESTADO_TICKET PRIMARY KEY (ETI_ID)
);

CREATE TABLE PAR_TIPO_COBRO (
    TCO_ID          NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    TCO_TIPO        VARCHAR2(50)  NOT NULL,
    TCO_DESCRIPCION VARCHAR2(500),
    CONSTRAINT PK_PAR_TIPO_COBRO PRIMARY KEY (TCO_ID)
);

CREATE TABLE PAR_TARIFA (
    TAR_ID            NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    TAR_TIPO          VARCHAR2(50)  NOT NULL,
    TAR_PRECIO        NUMBER(6,2),
    TAR_TIEMPO_GRACIA NUMBER(3),
    CONSTRAINT PK_PAR_TARIFA PRIMARY KEY (TAR_ID)
);

CREATE TABLE PAR_TICKET (
    TIC_ID                 NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    TIC_CODIGO             VARCHAR2(20) NOT NULL,
    VEH_ID                 NUMBER(10) NOT NULL,
    TIC_FECHA_HORA_ENTRADA DATE         NOT NULL,
    TIC_FECHA_HORA_SALIDA  DATE,
    ETI_ID                 NUMBER(10) NOT NULL,
    CONSTRAINT PK_PAR_TICKET PRIMARY KEY (TIC_ID),
    CONSTRAINT FK_PAR_TICKET_VEHICULO FOREIGN KEY (VEH_ID) REFERENCES PAR_VEHICULO(VEH_ID),
    CONSTRAINT FK_PAR_TICKET_ESTADO   FOREIGN KEY (ETI_ID) REFERENCES PAR_ESTADO_TICKET(ETI_ID)
);

CREATE TABLE PAR_COBRO (
    COB_ID                NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    TIC_ID                NUMBER(10) NOT NULL,
    COB_NIT               VARCHAR2(20),
    COB_HORAS_TOTALES     NUMBER(10,2)  NOT NULL,
    TCO_ID                NUMBER(10) NOT NULL,
    COB_MONTO_TOTAL       NUMBER(6,2)  NOT NULL,
    COB_MONTO_RECIBIDO    NUMBER(6,2),
    COB_VUELTO            NUMBER(6,2),
    COB_FECHA_HORA        DATE         NOT NULL,
    COB_PROCESADO_MAQUINA NUMBER(1),
    TAR_ID                NUMBER(10) NOT NULL,
    CONSTRAINT PK_PAR_COBRO PRIMARY KEY (COB_ID),
    CONSTRAINT UK_PAR_COBRO_TIC_ID UNIQUE (TIC_ID),
    CONSTRAINT FK_PAR_COBRO_TICKET     FOREIGN KEY (TIC_ID) REFERENCES PAR_TICKET(TIC_ID),
    CONSTRAINT FK_PAR_COBRO_TIPO_COBRO FOREIGN KEY (TCO_ID) REFERENCES PAR_TIPO_COBRO(TCO_ID),
    CONSTRAINT FK_PAR_COBRO_TARIFA     FOREIGN KEY (TAR_ID) REFERENCES PAR_TARIFA(TAR_ID)
);

CREATE TABLE PAR_TIPO_MAQUINA (
    TMA_ID          NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    TMA_TIPO        VARCHAR2(50)  NOT NULL,
    TMA_DESCRIPCION VARCHAR2(500),
    CONSTRAINT PK_PAR_TIPO_MAQUINA PRIMARY KEY (TMA_ID)
);

CREATE TABLE PAR_ESTADO_MAQUINA (
    EMA_ID          NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    EMA_ESTADO      VARCHAR2(50)  NOT NULL,
    EMA_DESCRIPCION VARCHAR2(500),
    CONSTRAINT PK_PAR_ESTADO_MAQUINA PRIMARY KEY (EMA_ID)
);

CREATE TABLE PAR_MAQUINA (
    MAQ_ID                   NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    MAQ_CODIGO               VARCHAR2(20) NOT NULL,
    TMA_ID                   NUMBER(10) NOT NULL,
    EMA_ID                   NUMBER(10) NOT NULL,
    MAQ_FECHA_ULTIMA_RECARGA DATE,
    CONSTRAINT PK_PAR_MAQUINA PRIMARY KEY (MAQ_ID),
    CONSTRAINT FK_PAR_MAQUINA_TIPO   FOREIGN KEY (TMA_ID) REFERENCES PAR_TIPO_MAQUINA(TMA_ID),
    CONSTRAINT FK_PAR_MAQUINA_ESTADO FOREIGN KEY (EMA_ID) REFERENCES PAR_ESTADO_MAQUINA(EMA_ID)
);

CREATE TABLE PAR_DETALLE_MAQUINA_TICKET (
    DMT_ID               NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    DMT_TRANSACCION      VARCHAR2(200),
    TIC_ID               NUMBER(10) NOT NULL,
    MAQ_ID               NUMBER(10) NOT NULL,
    DMT_HORA_TRANSACCION TIMESTAMP,
    CONSTRAINT PK_PAR_DETALLE_MAQUINA_TICKET PRIMARY KEY (DMT_ID),
    CONSTRAINT FK_PAR_DMT_TICKET  FOREIGN KEY (TIC_ID) REFERENCES PAR_TICKET(TIC_ID),
    CONSTRAINT FK_PAR_DMT_MAQUINA FOREIGN KEY (MAQ_ID) REFERENCES PAR_MAQUINA(MAQ_ID)
);

CREATE TABLE PAR_SALDO_DISPONIBLE (
    SDI_ID    NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    SDI_TIPO  VARCHAR2(50),
    SDI_VALOR NUMBER(6,2),
    CONSTRAINT PK_PAR_SALDO_DISPONIBLE PRIMARY KEY (SDI_ID)
);

CREATE TABLE PAR_DETALLE_SALDO (
    DSA_ID       NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    DSA_CANTIDAD NUMBER(10,2),
    DSA_SUBTOTAL NUMBER(10,2),
    DSA_UMBRAL_MINIMO NUMBER(5),
    SDI_ID       NUMBER(10) NOT NULL,
    MAQ_ID       NUMBER(10) NOT NULL,
    CONSTRAINT PK_PAR_DETALLE_SALDO PRIMARY KEY (DSA_ID),
    CONSTRAINT FK_PAR_DSA_SALDO_DISP FOREIGN KEY (SDI_ID) REFERENCES PAR_SALDO_DISPONIBLE(SDI_ID),
    CONSTRAINT FK_PAR_DSA_MAQUINA    FOREIGN KEY (MAQ_ID) REFERENCES PAR_MAQUINA(MAQ_ID)
);

CREATE TABLE PAR_RECARGO_MAQUINA (
    RMA_ID                  NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    MAQ_ID                  NUMBER(10) NOT NULL,
    RMA_MANTENIMIENTO_FECHA DATE,
    RMA_DESCRIPCION         VARCHAR2(500),
    CONSTRAINT PK_PAR_RECARGO_MAQUINA PRIMARY KEY (RMA_ID),
    CONSTRAINT FK_PAR_RMA_MAQUINA FOREIGN KEY (MAQ_ID) REFERENCES PAR_MAQUINA(MAQ_ID)
);

CREATE TABLE PAR_REGISTRO_MANTENIMIENTO (
    REM_ID                  NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    MAQ_ID                  NUMBER(10) NOT NULL,
    REM_MANTENIMIENTO_FECHA DATE,
    REM_DESCRIPCION         VARCHAR2(500),
    REM_TIPO_MOVIMIENTO     VARCHAR2(20),
    REM_ESTADO_RESULTANTE_EMA_ID NUMBER(10),
    CONSTRAINT PK_PAR_REGISTRO_MANTENIMIENTO PRIMARY KEY (REM_ID),
    CONSTRAINT FK_PAR_REM_MAQUINA FOREIGN KEY (MAQ_ID) REFERENCES PAR_MAQUINA(MAQ_ID),
    CONSTRAINT FK_PAR_REM_ESTADO_RESULTANTE FOREIGN KEY (REM_ESTADO_RESULTANTE_EMA_ID) REFERENCES PAR_ESTADO_MAQUINA(EMA_ID)
);

CREATE TABLE PAR_ESTADO_ALERTA (
    EAL_ID          NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    EAL_ESTADO      VARCHAR2(50)  NOT NULL,
    EAL_DESCRIPCION VARCHAR2(500),
    CONSTRAINT PK_PAR_ESTADO_ALERTA PRIMARY KEY (EAL_ID)
);

CREATE TABLE PAR_TIPO_ALERTA (
    TAL_ID          NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    TAL_TIPO        VARCHAR2(50)  NOT NULL,
    TAL_DESCRIPCION VARCHAR2(500),
    CONSTRAINT PK_PAR_TIPO_ALERTA PRIMARY KEY (TAL_ID)
);

CREATE TABLE PAR_ALERTA (
    ALE_ID                    NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    MAQ_ID                    NUMBER(10),
    ALE_MOTIVO                VARCHAR2(200),
    ALE_DESCRIPCION           CLOB,
    ALE_FECHA_HORA_GENERACION DATE         NOT NULL,
    EAL_ID                    NUMBER(10) NOT NULL,
    TAL_ID                    NUMBER(10) NOT NULL,
    ALE_FECHA_ATENCION        DATE,
    CONSTRAINT PK_PAR_ALERTA PRIMARY KEY (ALE_ID),
    CONSTRAINT FK_PAR_ALE_MAQUINA FOREIGN KEY (MAQ_ID) REFERENCES PAR_MAQUINA(MAQ_ID),
    CONSTRAINT FK_PAR_ALE_ESTADO  FOREIGN KEY (EAL_ID) REFERENCES PAR_ESTADO_ALERTA(EAL_ID),
    CONSTRAINT FK_PAR_ALE_TIPO    FOREIGN KEY (TAL_ID) REFERENCES PAR_TIPO_ALERTA(TAL_ID)
);

CREATE TABLE PAR_INCIDENTE (
    INC_ID          NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    INC_TIPO        VARCHAR2(50)  NOT NULL,
    INC_DESCRIPCION VARCHAR2(500),
    CONSTRAINT PK_PAR_INCIDENTE PRIMARY KEY (INC_ID)
);

CREATE TABLE PAR_ROL (
    ROL_ID          NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    ROL_TIPO        VARCHAR2(50)  NOT NULL,
    ROL_DESCRIPCION VARCHAR2(500),
    CONSTRAINT PK_PAR_ROL PRIMARY KEY (ROL_ID)
);

CREATE TABLE PAR_USUARIO (
    USU_ID                 NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    USU_PRIMER_NOMBRE      VARCHAR2(100) NOT NULL,
    USU_SEGUNDO_NOMBRE     VARCHAR2(100),
    USU_PRIMER_APELLIDO    VARCHAR2(100) NOT NULL,
    USU_SEGUNDO_APELLIDO   VARCHAR2(100),
    USU_CORREO             VARCHAR2(100) NOT NULL,
    USU_PASSWORD           VARCHAR2(100) NOT NULL,
    USU_TELEFONO           VARCHAR2(20),
    ROL_ID                 NUMBER(10) NOT NULL,
    USU_ACTIVO             NUMBER(1)    NOT NULL,
    USU_FECHA_CREACION     DATE         NOT NULL,
    USU_FECHA_ACTUALIZACION DATE,
    CONSTRAINT PK_PAR_USUARIO PRIMARY KEY (USU_ID),
    CONSTRAINT UK_PAR_USUARIO_CORREO UNIQUE (USU_CORREO),
    CONSTRAINT FK_PAR_USUARIO_ROL FOREIGN KEY (ROL_ID) REFERENCES PAR_ROL(ROL_ID)
);

CREATE TABLE PAR_BITACORA_INCIDENTE_VEHICULO (
    BIV_ID               NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    BIV_DESCRIPCION      VARCHAR2(500),
    BIV_FECHA_HORA       DATE         NOT NULL,
    VEH_ID               NUMBER(10) NOT NULL,
    INC_ID               NUMBER(10) NOT NULL,
    BIV_RESUELTO         NUMBER(1)    NOT NULL,
    BIV_FECHA_RESOLUCION DATE,
    USU_ID               NUMBER(10),
    CONSTRAINT PK_PAR_BITACORA_INCIDENTE_VEHICULO PRIMARY KEY (BIV_ID),
    CONSTRAINT FK_PAR_BIV_VEHICULO  FOREIGN KEY (VEH_ID) REFERENCES PAR_VEHICULO(VEH_ID),
    CONSTRAINT FK_PAR_BIV_INCIDENTE FOREIGN KEY (INC_ID) REFERENCES PAR_INCIDENTE(INC_ID),
    CONSTRAINT FK_PAR_BIV_USUARIO   FOREIGN KEY (USU_ID) REFERENCES PAR_USUARIO(USU_ID)
);

CREATE TABLE PAR_ESTADO_MEMBRESIA (
    EME_ID     NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    EME_ESTADO VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_PAR_ESTADO_MEMBRESIA PRIMARY KEY (EME_ID)
);

CREATE TABLE PAR_TIPO_MEMBRESIA (
    TME_ID          NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    TME_TIPO        VARCHAR2(50)   NOT NULL,
    TME_DESCRIPCION VARCHAR2(500),
    TME_DURACION    NUMBER(10)     NOT NULL,
    TME_PRECIO      NUMBER(6,2)    NOT NULL,
    CONSTRAINT PK_PAR_TIPO_MEMBRESIA PRIMARY KEY (TME_ID)
);

CREATE TABLE PAR_ESTADO_ESPACIO (
    EES_ID     NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    EES_ESTADO VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_PAR_ESTADO_ESPACIO PRIMARY KEY (EES_ID)
);

CREATE TABLE PAR_ESPACIO (
    ESP_ID        NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    ESP_CODIGO    VARCHAR2(20) NOT NULL,
    EES_ID        NUMBER(10),
    ESP_UBICACION VARCHAR2(200),
    CONSTRAINT PK_PAR_ESPACIO PRIMARY KEY (ESP_ID),
    CONSTRAINT FK_PAR_ESPACIO_ESTADO FOREIGN KEY (EES_ID) REFERENCES PAR_ESTADO_ESPACIO(EES_ID)
);

CREATE TABLE PAR_MEMBRESIA (
    MEM_ID                         NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    TME_ID                         NUMBER(10) NOT NULL,
    MEM_FECHA_INICIO               DATE         NOT NULL,
    EME_ID                         NUMBER(10),
    MEM_FECHA_VENCIMIENTO          DATE         NOT NULL,
    MEM_FECHA_ULTIMO_CAMBIO_ESTADO DATE,
    MEM_CODIGO VARCHAR2(25),
    VEH_ID                         NUMBER(10) NOT NULL,
    ESP_ID                         NUMBER(10) NOT NULL,
    CONSTRAINT PK_PAR_MEMBRESIA PRIMARY KEY (MEM_ID),
    CONSTRAINT FK_PAR_MEMBRESIA_TIPO     FOREIGN KEY (TME_ID) REFERENCES PAR_TIPO_MEMBRESIA(TME_ID),
    CONSTRAINT FK_PAR_MEMBRESIA_ESTADO     FOREIGN KEY (EME_ID) REFERENCES PAR_ESTADO_MEMBRESIA(EME_ID),
    CONSTRAINT FK_PAR_MEMBRESIA_VEHICULO   FOREIGN KEY (VEH_ID) REFERENCES PAR_VEHICULO(VEH_ID),
    CONSTRAINT FK_PAR_MEMBRESIA_ESPACIO    FOREIGN KEY (ESP_ID) REFERENCES PAR_ESPACIO(ESP_ID),
    CONSTRAINT UK_PAR_MEMBRESIA_VEH_ID UNIQUE (VEH_ID),
    CONSTRAINT UK_PAR_MEMBRESIA_ESP_ID UNIQUE (ESP_ID)
);

CREATE TABLE PAR_REGISTRO_MOVIMIENTO_MEMBRESIA (
    RMM_ID                 NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    RMM_FECHA_HORA_ENTRADA DATE,
    RMM_FECHA_HORA_SALIDA  DATE,
    MEM_ID                 NUMBER(10) NOT NULL,
    CONSTRAINT PK_PAR_REGISTRO_MOVIMIENTO_MEMBRESIA PRIMARY KEY (RMM_ID),
    CONSTRAINT FK_PAR_RMM_MEMBRESIA FOREIGN KEY (MEM_ID) REFERENCES PAR_MEMBRESIA(MEM_ID)
);

CREATE TABLE PAR_TIPO_PAGO (
    TPA_ID          NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    TPA_TIPO        VARCHAR2(50)  NOT NULL,
    TPA_DESCRIPCION VARCHAR2(500),
    CONSTRAINT PK_PAR_TIPO_PAGO PRIMARY KEY (TPA_ID)
);

CREATE TABLE PAR_PAGO (
    PAG_ID             NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    TPA_ID             NUMBER(10) NOT NULL,
    PAG_MONTO_TOTAL    NUMBER(6,2)  NOT NULL,
    PAG_MONTO_RECIBIDO NUMBER(6,2),
    PAG_VUELTO         NUMBER(6,2),
    PAG_FECHA_HORA     DATE         NOT NULL,
    CONSTRAINT PK_PAR_PAGO PRIMARY KEY (PAG_ID),
    CONSTRAINT FK_PAR_PAGO_TIPO_PAGO FOREIGN KEY (TPA_ID) REFERENCES PAR_TIPO_PAGO(TPA_ID)
);

CREATE TABLE PAR_DETALLE_PAGO_MEMBRESIA (
    DPM_ID            NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    MEM_ID            NUMBER(10) NOT NULL,
    PAG_ID            NUMBER(10) NOT NULL,
    DPM_MES_CANCELADO NUMBER(6,2)  NOT NULL,
    CONSTRAINT PK_PAR_DETALLE_PAGO_MEMBRESIA PRIMARY KEY (DPM_ID),
    CONSTRAINT FK_PAR_DPM_MEMBRESIA FOREIGN KEY (MEM_ID) REFERENCES PAR_MEMBRESIA(MEM_ID),
    CONSTRAINT FK_PAR_DPM_PAGO      FOREIGN KEY (PAG_ID) REFERENCES PAR_PAGO(PAG_ID)
);

CREATE TABLE PAR_TIPO_NOTIFICACION (
    TNO_ID          NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    TNO_TIPO        VARCHAR2(50)  NOT NULL,
    TNO_DESCRIPCION VARCHAR2(500),
    CONSTRAINT PK_PAR_TIPO_NOTIFICACION PRIMARY KEY (TNO_ID)
);

CREATE TABLE PAR_NOTIFICACION (
    NOT_ID                  NUMBER(10) GENERATED ALWAYS AS IDENTITY NOT NULL,
    TNO_ID                  NUMBER(10) NOT NULL,
    MEM_ID                  NUMBER(10) NOT NULL,
    NOT_ULTIMA_FECHA_ENVIO  DATE         NOT NULL,
    NOT_PROXIMA_FECHA_ENVIO DATE         NOT NULL,
    NOT_EXITO               NUMBER(1)    NOT NULL,
    CONSTRAINT PK_PAR_NOTIFICACION PRIMARY KEY (NOT_ID),
    CONSTRAINT FK_PAR_NOT_MEMBRESIA FOREIGN KEY (MEM_ID) REFERENCES PAR_MEMBRESIA(MEM_ID),
    CONSTRAINT FK_PAR_NOT_TIPO      FOREIGN KEY (TNO_ID) REFERENCES PAR_TIPO_NOTIFICACION(TNO_ID)
);

ALTER TABLE PAR_ALERTA ADD (
  ALE_USU_ID_RESOLVIO NUMBER,
  ALE_DESCRIPCION_SOLUCION VARCHAR2(1000)
);

ALTER TABLE PAR_ALERTA
  ADD CONSTRAINT FK_PAR_ALERTA_USU_RESOLVIO
  FOREIGN KEY (ALE_USU_ID_RESOLVIO)
  REFERENCES PAR_USUARIO (USU_ID);

ALTER TABLE PAR_NOTIFICACION ADD (
  NOT_ASUNTO VARCHAR2(200),
  NOT_CUERPO CLOB
);
