-- Datos demo HU. Tablas = PAR_ENTIDADES.sql (PKs GENERATED ALWAYS AS IDENTITY).
-- Cada INSERT declara la PK con DEFAULT para activar la identidad.

DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM PAR_ROL WHERE UPPER(ROL_TIPO) LIKE '%ADMIN%';
  IF c = 0 THEN
    INSERT INTO PAR_ROL (ROL_ID, ROL_TIPO, ROL_DESCRIPCION) VALUES (DEFAULT, 'Administrador', 'Rol demo panel');
  END IF;

  SELECT COUNT(*) INTO c FROM PAR_USUARIO WHERE LOWER(USU_CORREO) = 'admin@parqueo.demo';
  IF c = 0 THEN
    INSERT INTO PAR_USUARIO (USU_ID, USU_PRIMER_NOMBRE, USU_PRIMER_APELLIDO, USU_CORREO, USU_PASSWORD, ROL_ID, USU_ACTIVO, USU_FECHA_CREACION)
    VALUES (
      DEFAULT, 'Demo', 'QA', 'admin@parqueo.demo',
      'scrypt$MTIzNDU2Nzg5MDEy$gE8aK/9FncFvKCjUg2xeau+vVgMgoU5f5JQIUAuoOJ8=',
      (SELECT MIN(ROL_ID) FROM PAR_ROL), 1, SYSDATE
    );
  END IF;

  SELECT COUNT(*) INTO c FROM PAR_TIPO_VEHICULO WHERE LOWER(TVE_TIPO) LIKE '%automovil%';
  IF c = 0 THEN
    INSERT INTO PAR_TIPO_VEHICULO (TVE_ID, TVE_TIPO, TVE_DESCRIPCION) VALUES (DEFAULT, 'Automovil', 'Demo');
  END IF;

  SELECT COUNT(*) INTO c FROM PAR_ESTADO_TICKET WHERE LOWER(ETI_ESTADO) LIKE '%activ%';
  IF c = 0 THEN INSERT INTO PAR_ESTADO_TICKET (ETI_ID, ETI_ESTADO) VALUES (DEFAULT, 'Activo'); END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESTADO_TICKET WHERE LOWER(ETI_ESTADO) LIKE '%pagad%';
  IF c = 0 THEN INSERT INTO PAR_ESTADO_TICKET (ETI_ID, ETI_ESTADO) VALUES (DEFAULT, 'Pagado'); END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESTADO_TICKET WHERE LOWER(ETI_ESTADO) LIKE '%extrav%';
  IF c = 0 THEN INSERT INTO PAR_ESTADO_TICKET (ETI_ID, ETI_ESTADO) VALUES (DEFAULT, 'Extraviado'); END IF;

  SELECT COUNT(*) INTO c FROM PAR_TIPO_COBRO WHERE LOWER(TCO_TIPO) LIKE '%efect%';
  IF c = 0 THEN INSERT INTO PAR_TIPO_COBRO (TCO_ID, TCO_TIPO, TCO_DESCRIPCION) VALUES (DEFAULT, 'Efectivo', 'Cobro en efectivo demo'); END IF;
  SELECT COUNT(*) INTO c FROM PAR_TARIFA WHERE LOWER(TAR_TIPO) LIKE '%espor%';
  IF c = 0 THEN
    INSERT INTO PAR_TARIFA (TAR_ID, TAR_TIPO, TAR_PRECIO, TAR_TIEMPO_GRACIA) VALUES (DEFAULT, 'Esporádico hora', 10, 15);
  END IF;

  SELECT COUNT(*) INTO c FROM PAR_TIPO_MAQUINA WHERE LOWER(TMA_TIPO) LIKE '%cabin%';
  IF c = 0 THEN INSERT INTO PAR_TIPO_MAQUINA (TMA_ID, TMA_TIPO, TMA_DESCRIPCION) VALUES (DEFAULT, 'Cabina', 'Entrada / salida / cobro'); END IF;
  SELECT COUNT(*) INTO c FROM PAR_TIPO_MAQUINA WHERE LOWER(TMA_TIPO) = 'entrada';
  IF c = 0 THEN INSERT INTO PAR_TIPO_MAQUINA (TMA_ID, TMA_TIPO, TMA_DESCRIPCION) VALUES (DEFAULT, 'Entrada', 'Cabina de entrada'); END IF;
  SELECT COUNT(*) INTO c FROM PAR_TIPO_MAQUINA WHERE LOWER(TMA_TIPO) = 'salida';
  IF c = 0 THEN INSERT INTO PAR_TIPO_MAQUINA (TMA_ID, TMA_TIPO, TMA_DESCRIPCION) VALUES (DEFAULT, 'Salida', 'Cabina de salida'); END IF;
  SELECT COUNT(*) INTO c FROM PAR_TIPO_MAQUINA WHERE LOWER(TMA_TIPO) = 'cobro';
  IF c = 0 THEN INSERT INTO PAR_TIPO_MAQUINA (TMA_ID, TMA_TIPO, TMA_DESCRIPCION) VALUES (DEFAULT, 'Cobro', 'Máquina de cobro'); END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESTADO_MAQUINA WHERE LOWER(EMA_ESTADO) LIKE '%operat%';
  IF c = 0 THEN INSERT INTO PAR_ESTADO_MAQUINA (EMA_ID, EMA_ESTADO, EMA_DESCRIPCION) VALUES (DEFAULT, 'Operativa', 'En servicio'); END IF;

  UPDATE PAR_MAQUINA SET TMA_ID = (SELECT MIN(TMA_ID) FROM PAR_TIPO_MAQUINA WHERE LOWER(TMA_TIPO) = 'entrada')
    WHERE MAQ_CODIGO = 'DEMO-ENT'
      AND EXISTS (SELECT 1 FROM PAR_TIPO_MAQUINA WHERE LOWER(TMA_TIPO) = 'entrada');
  UPDATE PAR_MAQUINA SET TMA_ID = (SELECT MIN(TMA_ID) FROM PAR_TIPO_MAQUINA WHERE LOWER(TMA_TIPO) = 'salida')
    WHERE MAQ_CODIGO = 'DEMO-SAL'
      AND EXISTS (SELECT 1 FROM PAR_TIPO_MAQUINA WHERE LOWER(TMA_TIPO) = 'salida');
  UPDATE PAR_MAQUINA SET TMA_ID = (SELECT MIN(TMA_ID) FROM PAR_TIPO_MAQUINA WHERE LOWER(TMA_TIPO) = 'cobro')
    WHERE MAQ_CODIGO = 'DEMO-COB'
      AND EXISTS (SELECT 1 FROM PAR_TIPO_MAQUINA WHERE LOWER(TMA_TIPO) = 'cobro');

  SELECT COUNT(*) INTO c FROM PAR_MAQUINA WHERE MAQ_CODIGO = 'DEMO-ENT';
  IF c = 0 THEN
    INSERT INTO PAR_MAQUINA (MAQ_ID, MAQ_CODIGO, TMA_ID, EMA_ID)
    VALUES (DEFAULT, 'DEMO-ENT', (SELECT MIN(TMA_ID) FROM PAR_TIPO_MAQUINA), (SELECT MIN(EMA_ID) FROM PAR_ESTADO_MAQUINA));
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_MAQUINA WHERE MAQ_CODIGO = 'DEMO-SAL';
  IF c = 0 THEN
    INSERT INTO PAR_MAQUINA (MAQ_ID, MAQ_CODIGO, TMA_ID, EMA_ID)
    VALUES (DEFAULT, 'DEMO-SAL', (SELECT MIN(TMA_ID) FROM PAR_TIPO_MAQUINA), (SELECT MIN(EMA_ID) FROM PAR_ESTADO_MAQUINA));
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_MAQUINA WHERE MAQ_CODIGO = 'DEMO-COB';
  IF c = 0 THEN
    INSERT INTO PAR_MAQUINA (MAQ_ID, MAQ_CODIGO, TMA_ID, EMA_ID)
    VALUES (DEFAULT, 'DEMO-COB', (SELECT MIN(TMA_ID) FROM PAR_TIPO_MAQUINA), (SELECT MIN(EMA_ID) FROM PAR_ESTADO_MAQUINA));
  END IF;

  SELECT COUNT(*) INTO c FROM PAR_SALDO_DISPONIBLE WHERE SDI_VALOR = 5;
  IF c = 0 THEN INSERT INTO PAR_SALDO_DISPONIBLE (SDI_ID, SDI_TIPO, SDI_VALOR) VALUES (DEFAULT, 'Q5', 5); END IF;
  SELECT COUNT(*) INTO c FROM PAR_SALDO_DISPONIBLE WHERE SDI_VALOR = 10;
  IF c = 0 THEN INSERT INTO PAR_SALDO_DISPONIBLE (SDI_ID, SDI_TIPO, SDI_VALOR) VALUES (DEFAULT, 'Q10', 10); END IF;
  SELECT COUNT(*) INTO c FROM PAR_SALDO_DISPONIBLE WHERE SDI_VALOR = 20;
  IF c = 0 THEN INSERT INTO PAR_SALDO_DISPONIBLE (SDI_ID, SDI_TIPO, SDI_VALOR) VALUES (DEFAULT, 'Q20', 20); END IF;
  SELECT COUNT(*) INTO c FROM PAR_SALDO_DISPONIBLE WHERE SDI_VALOR = 50;
  IF c = 0 THEN INSERT INTO PAR_SALDO_DISPONIBLE (SDI_ID, SDI_TIPO, SDI_VALOR) VALUES (DEFAULT, 'Q50', 50); END IF;

  SELECT COUNT(*) INTO c FROM PAR_DETALLE_SALDO d
    JOIN PAR_SALDO_DISPONIBLE s ON s.SDI_ID = d.SDI_ID
    JOIN PAR_MAQUINA m ON m.MAQ_ID = d.MAQ_ID
    WHERE s.SDI_VALOR = 5 AND m.MAQ_CODIGO = 'DEMO-COB';
  IF c = 0 THEN
    INSERT INTO PAR_DETALLE_SALDO (DSA_CANTIDAD, DSA_SUBTOTAL, DSA_UMBRAL_MINIMO, SDI_ID, MAQ_ID)
    SELECT 80, 400, 5, s.SDI_ID, m.MAQ_ID
    FROM PAR_SALDO_DISPONIBLE s
    CROSS JOIN PAR_MAQUINA m
    WHERE s.SDI_VALOR = 5 AND m.MAQ_CODIGO = 'DEMO-COB';
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_DETALLE_SALDO d
    JOIN PAR_SALDO_DISPONIBLE s ON s.SDI_ID = d.SDI_ID
    JOIN PAR_MAQUINA m ON m.MAQ_ID = d.MAQ_ID
    WHERE s.SDI_VALOR = 10 AND m.MAQ_CODIGO = 'DEMO-COB';
  IF c = 0 THEN
    INSERT INTO PAR_DETALLE_SALDO (DSA_CANTIDAD, DSA_SUBTOTAL, DSA_UMBRAL_MINIMO, SDI_ID, MAQ_ID)
    SELECT 60, 600, 5, s.SDI_ID, m.MAQ_ID
    FROM PAR_SALDO_DISPONIBLE s
    CROSS JOIN PAR_MAQUINA m
    WHERE s.SDI_VALOR = 10 AND m.MAQ_CODIGO = 'DEMO-COB';
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_DETALLE_SALDO d
    JOIN PAR_SALDO_DISPONIBLE s ON s.SDI_ID = d.SDI_ID
    JOIN PAR_MAQUINA m ON m.MAQ_ID = d.MAQ_ID
    WHERE s.SDI_VALOR = 20 AND m.MAQ_CODIGO = 'DEMO-COB';
  IF c = 0 THEN
    INSERT INTO PAR_DETALLE_SALDO (DSA_CANTIDAD, DSA_SUBTOTAL, DSA_UMBRAL_MINIMO, SDI_ID, MAQ_ID)
    SELECT 40, 800, 3, s.SDI_ID, m.MAQ_ID
    FROM PAR_SALDO_DISPONIBLE s
    CROSS JOIN PAR_MAQUINA m
    WHERE s.SDI_VALOR = 20 AND m.MAQ_CODIGO = 'DEMO-COB';
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_DETALLE_SALDO d
    JOIN PAR_SALDO_DISPONIBLE s ON s.SDI_ID = d.SDI_ID
    JOIN PAR_MAQUINA m ON m.MAQ_ID = d.MAQ_ID
    WHERE s.SDI_VALOR = 50 AND m.MAQ_CODIGO = 'DEMO-COB';
  IF c = 0 THEN
    INSERT INTO PAR_DETALLE_SALDO (DSA_CANTIDAD, DSA_SUBTOTAL, DSA_UMBRAL_MINIMO, SDI_ID, MAQ_ID)
    SELECT 20, 1000, 2, s.SDI_ID, m.MAQ_ID
    FROM PAR_SALDO_DISPONIBLE s
    CROSS JOIN PAR_MAQUINA m
    WHERE s.SDI_VALOR = 50 AND m.MAQ_CODIGO = 'DEMO-COB';
  END IF;

  SELECT COUNT(*) INTO c FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E01';
  IF c = 0 THEN
    INSERT INTO PAR_ESPACIO (ESP_ID, ESP_CODIGO, EES_ID, ESP_UBICACION)
    VALUES (DEFAULT, 'DEMO-E01', (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
      WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%' AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'), 'Planta demo');
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E02';
  IF c = 0 THEN
    INSERT INTO PAR_ESPACIO (ESP_ID, ESP_CODIGO, EES_ID, ESP_UBICACION)
    VALUES (DEFAULT, 'DEMO-E02', (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
      WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%' AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'), 'Planta demo');
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E03';
  IF c = 0 THEN
    INSERT INTO PAR_ESPACIO (ESP_ID, ESP_CODIGO, EES_ID, ESP_UBICACION)
    VALUES (DEFAULT, 'DEMO-E03', (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
      WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%' AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'), 'Planta demo');
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E04';
  IF c = 0 THEN
    INSERT INTO PAR_ESPACIO (ESP_ID, ESP_CODIGO, EES_ID, ESP_UBICACION)
    VALUES (DEFAULT, 'DEMO-E04', (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
      WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%' AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'), 'Planta demo');
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E05';
  IF c = 0 THEN
    INSERT INTO PAR_ESPACIO (ESP_ID, ESP_CODIGO, EES_ID, ESP_UBICACION)
    VALUES (DEFAULT, 'DEMO-E05', (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
      WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%' AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'), 'Planta demo');
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E06';
  IF c = 0 THEN
    INSERT INTO PAR_ESPACIO (ESP_ID, ESP_CODIGO, EES_ID, ESP_UBICACION)
    VALUES (DEFAULT, 'DEMO-E06', (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
      WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%' AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'), 'Planta demo');
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E07';
  IF c = 0 THEN
    INSERT INTO PAR_ESPACIO (ESP_ID, ESP_CODIGO, EES_ID, ESP_UBICACION)
    VALUES (DEFAULT, 'DEMO-E07', (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
      WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%' AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'), 'Planta demo');
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E08';
  IF c = 0 THEN
    INSERT INTO PAR_ESPACIO (ESP_ID, ESP_CODIGO, EES_ID, ESP_UBICACION)
    VALUES (DEFAULT, 'DEMO-E08', (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
      WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%' AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'), 'Planta demo');
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E09';
  IF c = 0 THEN
    INSERT INTO PAR_ESPACIO (ESP_ID, ESP_CODIGO, EES_ID, ESP_UBICACION)
    VALUES (DEFAULT, 'DEMO-E09', (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
      WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%' AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'), 'Planta demo');
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E10';
  IF c = 0 THEN
    INSERT INTO PAR_ESPACIO (ESP_ID, ESP_CODIGO, EES_ID, ESP_UBICACION)
    VALUES (DEFAULT, 'DEMO-E10', (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
      WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%' AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'), 'Planta demo');
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E11';
  IF c = 0 THEN
    INSERT INTO PAR_ESPACIO (ESP_ID, ESP_CODIGO, EES_ID, ESP_UBICACION)
    VALUES (DEFAULT, 'DEMO-E11', (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
      WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%' AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'), 'Planta demo');
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E12';
  IF c = 0 THEN
    INSERT INTO PAR_ESPACIO (ESP_ID, ESP_CODIGO, EES_ID, ESP_UBICACION)
    VALUES (DEFAULT, 'DEMO-E12', (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
      WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%' AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'), 'Planta demo');
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-M01';
  IF c = 0 THEN
    INSERT INTO PAR_ESPACIO (ESP_ID, ESP_CODIGO, EES_ID, ESP_UBICACION)
    VALUES (DEFAULT, 'DEMO-M01', (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
      WHERE LOWER(e.EES_ESTADO) LIKE '%reserv%'
        AND (LOWER(e.EES_ESTADO) LIKE '%libre%' OR LOWER(e.EES_ESTADO) LIKE '%dispon%')), 'Mensual demo');
  END IF;

  SELECT COUNT(*) INTO c FROM PAR_CLIENTE WHERE CLI_CORREO = 'mensual@parqueo.demo';
  IF c = 0 THEN
    INSERT INTO PAR_CLIENTE (CLI_ID, CLI_PRIMER_NOMBRE, CLI_PRIMER_APELLIDO, CLI_DPI, CLI_CORREO, CLI_ACTIVO, CLI_FECHA_REGISTRO)
    VALUES (DEFAULT, 'Cliente', 'Mensual', 'DEMO1234567890101', 'mensual@parqueo.demo', 1, SYSDATE);
  END IF;

  SELECT COUNT(*) INTO c FROM PAR_VEHICULO WHERE VEH_PLACA = 'P99D001';
  IF c = 0 THEN
    INSERT INTO PAR_VEHICULO (VEH_ID, VEH_PLACA, VEH_MODELO, VEH_COLOR, TVE_ID, CLI_ID)
    VALUES (DEFAULT, 'P99D001', 'Yaris', 'Gris', (SELECT MIN(TVE_ID) FROM PAR_TIPO_VEHICULO), NULL);
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_VEHICULO WHERE VEH_PLACA = 'M88D001';
  IF c = 0 THEN
    INSERT INTO PAR_VEHICULO (VEH_ID, VEH_PLACA, VEH_MODELO, VEH_COLOR, TVE_ID, CLI_ID)
    VALUES (DEFAULT, 'M88D001', 'CX-5', 'Azul', (SELECT MIN(TVE_ID) FROM PAR_TIPO_VEHICULO),
      (SELECT MIN(CLI_ID) FROM PAR_CLIENTE WHERE CLI_CORREO = 'mensual@parqueo.demo'));
  END IF;

  SELECT COUNT(*) INTO c FROM PAR_ESTADO_MEMBRESIA WHERE LOWER(EME_ESTADO) LIKE '%activ%';
  IF c = 0 THEN INSERT INTO PAR_ESTADO_MEMBRESIA (EME_ID, EME_ESTADO) VALUES (DEFAULT, 'Activa'); END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESTADO_MEMBRESIA WHERE LOWER(EME_ESTADO) LIKE '%suspend%';
  IF c = 0 THEN INSERT INTO PAR_ESTADO_MEMBRESIA (EME_ID, EME_ESTADO) VALUES (DEFAULT, 'Suspendida'); END IF;
  SELECT COUNT(*) INTO c FROM PAR_TIPO_MEMBRESIA WHERE LOWER(TME_TIPO) LIKE '%mensual demo%';
  IF c = 0 THEN
    INSERT INTO PAR_TIPO_MEMBRESIA (TME_ID, TME_TIPO, TME_DURACION, TME_PRECIO, TME_DESCRIPCION)
    VALUES (DEFAULT, 'Mensual demo', 30, 500, 'Plan mensual QA');
  END IF;

  SELECT COUNT(*) INTO c FROM PAR_MEMBRESIA m
    JOIN PAR_VEHICULO v ON v.VEH_ID = m.VEH_ID
    WHERE v.VEH_PLACA = 'M88D001';
  IF c = 0 THEN
    INSERT INTO PAR_MEMBRESIA (MEM_ID, TME_ID, MEM_FECHA_INICIO, EME_ID, MEM_FECHA_VENCIMIENTO, MEM_CODIGO, VEH_ID, ESP_ID)
    VALUES (
      DEFAULT,
      (SELECT MIN(TME_ID) FROM PAR_TIPO_MEMBRESIA WHERE LOWER(TME_TIPO) LIKE '%mensual demo%'),
      SYSDATE - 10,
      (SELECT MIN(EME_ID) FROM PAR_ESTADO_MEMBRESIA WHERE LOWER(EME_ESTADO) LIKE '%activ%'),
      SYSDATE + 20,
      '010426DEMOMEM01',
      (SELECT VEH_ID FROM PAR_VEHICULO WHERE VEH_PLACA = 'M88D001'),
      (SELECT ESP_ID FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-M01')
    );
  END IF;

  SELECT COUNT(*) INTO c FROM PAR_TIPO_PAGO WHERE LOWER(TPA_TIPO) LIKE '%efect%';
  IF c = 0 THEN INSERT INTO PAR_TIPO_PAGO (TPA_ID, TPA_TIPO, TPA_DESCRIPCION) VALUES (DEFAULT, 'Efectivo', 'Pago en ventanilla'); END IF;

  SELECT COUNT(*) INTO c FROM PAR_INCIDENTE WHERE UPPER(INC_TIPO) = 'ESTACIONAMIENTO';
  IF c = 0 THEN INSERT INTO PAR_INCIDENTE (INC_ID, INC_TIPO, INC_DESCRIPCION) VALUES (DEFAULT, 'Estacionamiento', 'Incidente demo QA'); END IF;

  -- Al menos 500 espacios (carga masiva si faltan filas)
  SELECT COUNT(*) INTO c FROM PAR_ESPACIO;
  IF c < 500 THEN
    FOR i IN 1 .. (500 - c) LOOP
      INSERT INTO PAR_ESPACIO (ESP_ID, ESP_CODIGO, EES_ID, ESP_UBICACION)
      VALUES (
        DEFAULT,
        'BL-' || LPAD(TO_CHAR(c + i), 5, '0'),
        (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
          WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%' AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'),
        'Lote demo'
      );
    END LOOP;
  END IF;
END;
