-- DML de apoyo. Las tablas deben existir según PAR_ENTIDADES.sql (PKs GENERATED ALWAYS AS IDENTITY).
-- INSERT lista la PK con DEFAULT para que Oracle rellene la secuencia de identidad.

DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*) INTO c FROM PAR_ESTADO_ALERTA WHERE EAL_ESTADO = 'Pendiente';
  IF c = 0 THEN
    INSERT INTO PAR_ESTADO_ALERTA (EAL_ID, EAL_ESTADO, EAL_DESCRIPCION) VALUES (DEFAULT, 'Pendiente', 'Sin atender');
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESTADO_ALERTA WHERE EAL_ESTADO = 'Atendida';
  IF c = 0 THEN
    INSERT INTO PAR_ESTADO_ALERTA (EAL_ID, EAL_ESTADO, EAL_DESCRIPCION) VALUES (DEFAULT, 'Atendida', 'Ya gestionada');
  END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESTADO_ALERTA WHERE EAL_ESTADO = 'Activa';
  IF c = 0 THEN
    INSERT INTO PAR_ESTADO_ALERTA (EAL_ID, EAL_ESTADO, EAL_DESCRIPCION) VALUES (DEFAULT, 'Activa', 'Alerta vigente en panel');
  END IF;

  SELECT COUNT(*) INTO c FROM PAR_ESTADO_ESPACIO WHERE EES_ESTADO = 'Disponible';
  IF c = 0 THEN INSERT INTO PAR_ESTADO_ESPACIO (EES_ID, EES_ESTADO) VALUES (DEFAULT, 'Disponible'); END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESTADO_ESPACIO WHERE EES_ESTADO = 'Ocupado';
  IF c = 0 THEN INSERT INTO PAR_ESTADO_ESPACIO (EES_ID, EES_ESTADO) VALUES (DEFAULT, 'Ocupado'); END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESTADO_ESPACIO WHERE EES_ESTADO = 'Reservado Libre';
  IF c = 0 THEN INSERT INTO PAR_ESTADO_ESPACIO (EES_ID, EES_ESTADO) VALUES (DEFAULT, 'Reservado Libre'); END IF;
  SELECT COUNT(*) INTO c FROM PAR_ESTADO_ESPACIO WHERE EES_ESTADO = 'Reservado Ocupado';
  IF c = 0 THEN INSERT INTO PAR_ESTADO_ESPACIO (EES_ID, EES_ESTADO) VALUES (DEFAULT, 'Reservado Ocupado'); END IF;

  SELECT COUNT(*) INTO c FROM PAR_TIPO_NOTIFICACION WHERE TNO_TIPO = 'Recordatorio -3d';
  IF c = 0 THEN INSERT INTO PAR_TIPO_NOTIFICACION (TNO_ID, TNO_TIPO, TNO_DESCRIPCION) VALUES (DEFAULT, 'Recordatorio -3d', 'Tres días antes del vencimiento'); END IF;
  SELECT COUNT(*) INTO c FROM PAR_TIPO_NOTIFICACION WHERE TNO_TIPO = 'Recordatorio -2d';
  IF c = 0 THEN INSERT INTO PAR_TIPO_NOTIFICACION (TNO_ID, TNO_TIPO, TNO_DESCRIPCION) VALUES (DEFAULT, 'Recordatorio -2d', 'Dos días antes del vencimiento'); END IF;
  SELECT COUNT(*) INTO c FROM PAR_TIPO_NOTIFICACION WHERE TNO_TIPO = 'Recordatorio venc';
  IF c = 0 THEN INSERT INTO PAR_TIPO_NOTIFICACION (TNO_ID, TNO_TIPO, TNO_DESCRIPCION) VALUES (DEFAULT, 'Recordatorio venc', 'Día del vencimiento'); END IF;
  SELECT COUNT(*) INTO c FROM PAR_TIPO_NOTIFICACION WHERE TNO_TIPO = 'Recordatorio +1d';
  IF c = 0 THEN INSERT INTO PAR_TIPO_NOTIFICACION (TNO_ID, TNO_TIPO, TNO_DESCRIPCION) VALUES (DEFAULT, 'Recordatorio +1d', 'Día siguiente al vencimiento'); END IF;
  SELECT COUNT(*) INTO c FROM PAR_TIPO_NOTIFICACION WHERE TNO_TIPO = 'Suspensión mora';
  IF c = 0 THEN INSERT INTO PAR_TIPO_NOTIFICACION (TNO_ID, TNO_TIPO, TNO_DESCRIPCION) VALUES (DEFAULT, 'Suspensión mora', 'Notificación de suspensión automática por mora'); END IF;

  SELECT COUNT(*) INTO c FROM PAR_TIPO_ALERTA WHERE TAL_TIPO = 'Saldo bajo máquina';
  IF c = 0 THEN INSERT INTO PAR_TIPO_ALERTA (TAL_ID, TAL_TIPO, TAL_DESCRIPCION) VALUES (DEFAULT, 'Saldo bajo máquina', 'Efectivo por debajo del umbral en máquina de cobro'); END IF;
  SELECT COUNT(*) INTO c FROM PAR_TIPO_ALERTA WHERE TAL_TIPO = 'Sistema';
  IF c = 0 THEN INSERT INTO PAR_TIPO_ALERTA (TAL_ID, TAL_TIPO, TAL_DESCRIPCION) VALUES (DEFAULT, 'Sistema', 'Alertas generadas por procesos automáticos o fallos de integración'); END IF;
  SELECT COUNT(*) INTO c FROM PAR_TIPO_ALERTA WHERE TAL_TIPO = 'Asistencia cabina';
  IF c = 0 THEN INSERT INTO PAR_TIPO_ALERTA (TAL_ID, TAL_TIPO, TAL_DESCRIPCION) VALUES (DEFAULT, 'Asistencia cabina', 'Solicitud de asistencia desde máquina de entrada, salida o cobro'); END IF;
END;
