-- Datos demo para pruebas HU (DML). DDL = PAR_ENTIDADES.sql (sin cambios).
-- Idempotente: usa NOT EXISTS / códigos DEMO-*.
-- Contraseña usuario demo: Admin123!  (hash scrypt compatible con server/services/usuario.js)

-- Rol admin
INSERT INTO PAR_ROL (ROL_TIPO, ROL_DESCRIPCION)
SELECT 'Administrador', 'Rol demo panel' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_ROL WHERE UPPER(ROL_TIPO) LIKE '%ADMIN%');

-- Usuario demo (correo fijo)
INSERT INTO PAR_USUARIO (
  USU_PRIMER_NOMBRE, USU_PRIMER_APELLIDO, USU_CORREO, USU_PASSWORD,
  ROL_ID, USU_ACTIVO, USU_FECHA_CREACION
)
SELECT
  'Demo',
  'QA',
  'admin@parqueo.demo',
  'scrypt$MTIzNDU2Nzg5MDEy$gE8aK/9FncFvKCjUg2xeau+vVgMgoU5f5JQIUAuoOJ8=',
  (SELECT MIN(ROL_ID) FROM PAR_ROL),
  1,
  SYSDATE
FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_USUARIO WHERE LOWER(USU_CORREO) = 'admin@parqueo.demo');

-- Tipo vehículo
INSERT INTO PAR_TIPO_VEHICULO (TVE_TIPO, TVE_DESCRIPCION)
SELECT 'Automovil', 'Demo' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_TIPO_VEHICULO WHERE LOWER(TVE_TIPO) LIKE '%automovil%');

-- Estados ticket
INSERT INTO PAR_ESTADO_TICKET (ETI_ESTADO)
SELECT 'Activo' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_ESTADO_TICKET WHERE LOWER(ETI_ESTADO) LIKE '%activ%');

INSERT INTO PAR_ESTADO_TICKET (ETI_ESTADO)
SELECT 'Pagado' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_ESTADO_TICKET WHERE LOWER(ETI_ESTADO) LIKE '%pagad%');

INSERT INTO PAR_ESTADO_TICKET (ETI_ESTADO)
SELECT 'Extraviado' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_ESTADO_TICKET WHERE LOWER(ETI_ESTADO) LIKE '%extrav%');

-- Tipo cobro y tarifa
INSERT INTO PAR_TIPO_COBRO (TCO_TIPO, TCO_DESCRIPCION)
SELECT 'Efectivo', 'Cobro en efectivo demo' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_TIPO_COBRO WHERE LOWER(TCO_TIPO) LIKE '%efect%');

INSERT INTO PAR_TARIFA (TAR_TIPO, TAR_PRECIO, TAR_TIEMPO_GRACIA)
SELECT 'Esporádico hora', 10, 15 FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_TARIFA WHERE LOWER(TAR_TIPO) LIKE '%espor%');

-- Tipo / estado máquina
INSERT INTO PAR_TIPO_MAQUINA (TMA_TIPO, TMA_DESCRIPCION)
SELECT 'Cabina', 'Entrada / salida / cobro' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_TIPO_MAQUINA WHERE LOWER(TMA_TIPO) LIKE '%cabin%');

INSERT INTO PAR_ESTADO_MAQUINA (EMA_ESTADO, EMA_DESCRIPCION)
SELECT 'Operativa', 'En servicio' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_ESTADO_MAQUINA WHERE LOWER(EMA_ESTADO) LIKE '%operat%');

-- Tres máquinas demo (entrada, salida, cobro)
INSERT INTO PAR_MAQUINA (MAQ_CODIGO, TMA_ID, EMA_ID)
SELECT 'DEMO-ENT',
       (SELECT MIN(TMA_ID) FROM PAR_TIPO_MAQUINA),
       (SELECT MIN(EMA_ID) FROM PAR_ESTADO_MAQUINA)
FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_MAQUINA WHERE MAQ_CODIGO = 'DEMO-ENT');

INSERT INTO PAR_MAQUINA (MAQ_CODIGO, TMA_ID, EMA_ID)
SELECT 'DEMO-SAL',
       (SELECT MIN(TMA_ID) FROM PAR_TIPO_MAQUINA),
       (SELECT MIN(EMA_ID) FROM PAR_ESTADO_MAQUINA)
FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_MAQUINA WHERE MAQ_CODIGO = 'DEMO-SAL');

INSERT INTO PAR_MAQUINA (MAQ_CODIGO, TMA_ID, EMA_ID)
SELECT 'DEMO-COB',
       (SELECT MIN(TMA_ID) FROM PAR_TIPO_MAQUINA),
       (SELECT MIN(EMA_ID) FROM PAR_ESTADO_MAQUINA)
FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_MAQUINA WHERE MAQ_CODIGO = 'DEMO-COB');

-- Billetes para máquina de cobro (denominaciones)
INSERT INTO PAR_SALDO_DISPONIBLE (SDI_TIPO, SDI_VALOR)
SELECT 'Q5', 5 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PAR_SALDO_DISPONIBLE WHERE SDI_VALOR = 5);

INSERT INTO PAR_SALDO_DISPONIBLE (SDI_TIPO, SDI_VALOR)
SELECT 'Q10', 10 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PAR_SALDO_DISPONIBLE WHERE SDI_VALOR = 10);

INSERT INTO PAR_SALDO_DISPONIBLE (SDI_TIPO, SDI_VALOR)
SELECT 'Q20', 20 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PAR_SALDO_DISPONIBLE WHERE SDI_VALOR = 20);

INSERT INTO PAR_SALDO_DISPONIBLE (SDI_TIPO, SDI_VALOR)
SELECT 'Q50', 50 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PAR_SALDO_DISPONIBLE WHERE SDI_VALOR = 50);

-- Detalle saldo: billetes suficientes para vuelto (máquina DEMO-COB)
INSERT INTO PAR_DETALLE_SALDO (DSA_CANTIDAD, DSA_SUBTOTAL, DSA_UMBRAL_MINIMO, SDI_ID, MAQ_ID)
SELECT 80, 400, 5, s.SDI_ID, m.MAQ_ID
FROM PAR_SALDO_DISPONIBLE s
CROSS JOIN PAR_MAQUINA m
WHERE s.SDI_VALOR = 5 AND m.MAQ_CODIGO = 'DEMO-COB'
  AND NOT EXISTS (
    SELECT 1 FROM PAR_DETALLE_SALDO d WHERE d.SDI_ID = s.SDI_ID AND d.MAQ_ID = m.MAQ_ID);

INSERT INTO PAR_DETALLE_SALDO (DSA_CANTIDAD, DSA_SUBTOTAL, DSA_UMBRAL_MINIMO, SDI_ID, MAQ_ID)
SELECT 60, 600, 5, s.SDI_ID, m.MAQ_ID
FROM PAR_SALDO_DISPONIBLE s
CROSS JOIN PAR_MAQUINA m
WHERE s.SDI_VALOR = 10 AND m.MAQ_CODIGO = 'DEMO-COB'
  AND NOT EXISTS (
    SELECT 1 FROM PAR_DETALLE_SALDO d WHERE d.SDI_ID = s.SDI_ID AND d.MAQ_ID = m.MAQ_ID);

INSERT INTO PAR_DETALLE_SALDO (DSA_CANTIDAD, DSA_SUBTOTAL, DSA_UMBRAL_MINIMO, SDI_ID, MAQ_ID)
SELECT 40, 800, 3, s.SDI_ID, m.MAQ_ID
FROM PAR_SALDO_DISPONIBLE s
CROSS JOIN PAR_MAQUINA m
WHERE s.SDI_VALOR = 20 AND m.MAQ_CODIGO = 'DEMO-COB'
  AND NOT EXISTS (
    SELECT 1 FROM PAR_DETALLE_SALDO d WHERE d.SDI_ID = s.SDI_ID AND d.MAQ_ID = m.MAQ_ID);

INSERT INTO PAR_DETALLE_SALDO (DSA_CANTIDAD, DSA_SUBTOTAL, DSA_UMBRAL_MINIMO, SDI_ID, MAQ_ID)
SELECT 20, 1000, 2, s.SDI_ID, m.MAQ_ID
FROM PAR_SALDO_DISPONIBLE s
CROSS JOIN PAR_MAQUINA m
WHERE s.SDI_VALOR = 50 AND m.MAQ_CODIGO = 'DEMO-COB'
  AND NOT EXISTS (
    SELECT 1 FROM PAR_DETALLE_SALDO d WHERE d.SDI_ID = s.SDI_ID AND d.MAQ_ID = m.MAQ_ID);

-- Espacios esporádicos (disponibles): DEMO-E01 .. DEMO-E12
INSERT INTO PAR_ESPACIO (ESP_CODIGO, EES_ID, ESP_UBICACION)
SELECT 'DEMO-E01',
       (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
         WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%'
           AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'),
       'Planta demo'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E01');

INSERT INTO PAR_ESPACIO (ESP_CODIGO, EES_ID, ESP_UBICACION)
SELECT 'DEMO-E02',
       (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
         WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%'
           AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'),
       'Planta demo'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E02');

INSERT INTO PAR_ESPACIO (ESP_CODIGO, EES_ID, ESP_UBICACION)
SELECT 'DEMO-E03',
       (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
         WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%'
           AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'),
       'Planta demo'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E03');

INSERT INTO PAR_ESPACIO (ESP_CODIGO, EES_ID, ESP_UBICACION)
SELECT 'DEMO-E04',
       (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
         WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%'
           AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'),
       'Planta demo'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E04');

INSERT INTO PAR_ESPACIO (ESP_CODIGO, EES_ID, ESP_UBICACION)
SELECT 'DEMO-E05',
       (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
         WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%'
           AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'),
       'Planta demo'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E05');

INSERT INTO PAR_ESPACIO (ESP_CODIGO, EES_ID, ESP_UBICACION)
SELECT 'DEMO-E06',
       (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
         WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%'
           AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'),
       'Planta demo'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E06');

INSERT INTO PAR_ESPACIO (ESP_CODIGO, EES_ID, ESP_UBICACION)
SELECT 'DEMO-E07',
       (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
         WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%'
           AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'),
       'Planta demo'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E07');

INSERT INTO PAR_ESPACIO (ESP_CODIGO, EES_ID, ESP_UBICACION)
SELECT 'DEMO-E08',
       (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
         WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%'
           AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'),
       'Planta demo'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E08');

INSERT INTO PAR_ESPACIO (ESP_CODIGO, EES_ID, ESP_UBICACION)
SELECT 'DEMO-E09',
       (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
         WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%'
           AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'),
       'Planta demo'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E09');

INSERT INTO PAR_ESPACIO (ESP_CODIGO, EES_ID, ESP_UBICACION)
SELECT 'DEMO-E10',
       (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
         WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%'
           AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'),
       'Planta demo'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E10');

INSERT INTO PAR_ESPACIO (ESP_CODIGO, EES_ID, ESP_UBICACION)
SELECT 'DEMO-E11',
       (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
         WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%'
           AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'),
       'Planta demo'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E11');

INSERT INTO PAR_ESPACIO (ESP_CODIGO, EES_ID, ESP_UBICACION)
SELECT 'DEMO-E12',
       (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
         WHERE LOWER(e.EES_ESTADO) LIKE '%dispon%'
           AND LOWER(e.EES_ESTADO) NOT LIKE '%reserv%'),
       'Planta demo'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-E12');

-- Espacio mensual (reservado libre)
INSERT INTO PAR_ESPACIO (ESP_CODIGO, EES_ID, ESP_UBICACION)
SELECT 'DEMO-M01',
       (SELECT MIN(e.EES_ID) FROM PAR_ESTADO_ESPACIO e
         WHERE LOWER(e.EES_ESTADO) LIKE '%reserv%'
           AND (LOWER(e.EES_ESTADO) LIKE '%libre%' OR LOWER(e.EES_ESTADO) LIKE '%dispon%')),
       'Mensual demo'
FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-M01');

-- Cliente mensual
INSERT INTO PAR_CLIENTE (
  CLI_PRIMER_NOMBRE, CLI_PRIMER_APELLIDO, CLI_DPI, CLI_CORREO, CLI_ACTIVO, CLI_FECHA_REGISTRO
)
SELECT 'Cliente', 'Mensual', 'DEMO1234567890101', 'mensual@parqueo.demo', 1, SYSDATE
FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_CLIENTE WHERE CLI_CORREO = 'mensual@parqueo.demo');

-- Vehículo esporádico (sin cliente)
INSERT INTO PAR_VEHICULO (VEH_PLACA, VEH_MODELO, VEH_COLOR, TVE_ID, CLI_ID)
SELECT 'P99D001', 'Yaris', 'Gris',
       (SELECT MIN(TVE_ID) FROM PAR_TIPO_VEHICULO),
       NULL
FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_VEHICULO WHERE VEH_PLACA = 'P99D001');

-- Vehículo mensual (VEH_PLACA VARCHAR2(7))
INSERT INTO PAR_VEHICULO (VEH_PLACA, VEH_MODELO, VEH_COLOR, TVE_ID, CLI_ID)
SELECT 'M88D001', 'CX-5', 'Azul',
       (SELECT MIN(TVE_ID) FROM PAR_TIPO_VEHICULO),
       (SELECT MIN(CLI_ID) FROM PAR_CLIENTE WHERE CLI_CORREO = 'mensual@parqueo.demo')
FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_VEHICULO WHERE VEH_PLACA = 'M88D001');

-- Estados / tipo membresía
INSERT INTO PAR_ESTADO_MEMBRESIA (EME_ESTADO)
SELECT 'Activa' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_ESTADO_MEMBRESIA WHERE LOWER(EME_ESTADO) LIKE '%activ%');

INSERT INTO PAR_ESTADO_MEMBRESIA (EME_ESTADO)
SELECT 'Suspendida' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_ESTADO_MEMBRESIA WHERE LOWER(EME_ESTADO) LIKE '%suspend%');

INSERT INTO PAR_TIPO_MEMBRESIA (TME_TIPO, TME_DURACION, TME_PRECIO, TME_DESCRIPCION)
SELECT 'Mensual demo', 30, 500, 'Plan mensual QA' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_TIPO_MEMBRESIA WHERE LOWER(TME_TIPO) LIKE '%mensual demo%');

-- Membresía activa (MEM_CODIGO fijo para PDF/tag)
INSERT INTO PAR_MEMBRESIA (
  TME_ID, MEM_FECHA_INICIO, EME_ID, MEM_FECHA_VENCIMIENTO,
  MEM_CODIGO, VEH_ID, ESP_ID
)
SELECT
  (SELECT MIN(TME_ID) FROM PAR_TIPO_MEMBRESIA WHERE LOWER(TME_TIPO) LIKE '%mensual demo%'),
  SYSDATE - 10,
  (SELECT MIN(EME_ID) FROM PAR_ESTADO_MEMBRESIA WHERE LOWER(EME_ESTADO) LIKE '%activ%'),
  SYSDATE + 20,
  '010426DEMOMEM01',
  (SELECT VEH_ID FROM PAR_VEHICULO WHERE VEH_PLACA = 'M88D001'),
  (SELECT ESP_ID FROM PAR_ESPACIO WHERE ESP_CODIGO = 'DEMO-M01')
FROM DUAL
 WHERE NOT EXISTS (
   SELECT 1 FROM PAR_MEMBRESIA m
    JOIN PAR_VEHICULO v ON v.VEH_ID = m.VEH_ID
   WHERE v.VEH_PLACA = 'M88D001');

-- Tipo pago (mensualidades)
INSERT INTO PAR_TIPO_PAGO (TPA_TIPO, TPA_DESCRIPCION)
SELECT 'Efectivo', 'Pago en ventanilla' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_TIPO_PAGO WHERE LOWER(TPA_TIPO) LIKE '%efect%');

-- Incidente (bitácora)
INSERT INTO PAR_INCIDENTE (INC_TIPO, INC_DESCRIPCION)
SELECT 'Estacionamiento', 'Incidente demo QA' FROM DUAL
 WHERE NOT EXISTS (SELECT 1 FROM PAR_INCIDENTE WHERE UPPER(INC_TIPO) = 'ESTACIONAMIENTO');

COMMIT;
