-- Campos para resolución de alertas:
-- - ALE_USU_ID_RESOLVIO: usuario que resolvió
-- - ALE_DESCRIPCION_SOLUCION: detalle de la solución aplicada

ALTER TABLE PAR_ALERTA ADD (
  ALE_USU_ID_RESOLVIO NUMBER,
  ALE_DESCRIPCION_SOLUCION VARCHAR2(1000)
);

ALTER TABLE PAR_ALERTA
  ADD CONSTRAINT FK_PAR_ALERTA_USU_RESOLVIO
  FOREIGN KEY (ALE_USU_ID_RESOLVIO)
  REFERENCES PAR_USUARIO (USU_ID);
