DECLARE
  c NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO c
    FROM PAR_ESTADO_MAQUINA
   WHERE UPPER(TRIM(EMA_ESTADO)) = 'INOPERATIVA';

  IF c = 0 THEN
    INSERT INTO PAR_ESTADO_MAQUINA (EMA_ESTADO, EMA_DESCRIPCION)
    VALUES ('Inoperativa', 'Creada pero aún no activada');
    COMMIT;
  END IF;
END;
/
