DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'PAR_REGISTRO_MANTENIMIENTO'
     AND COLUMN_NAME = 'REM_TIPO_MOVIMIENTO';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PAR_REGISTRO_MANTENIMIENTO ADD (REM_TIPO_MOVIMIENTO VARCHAR2(20))';
  END IF;

  SELECT COUNT(*)
    INTO v_count
    FROM USER_TAB_COLUMNS
   WHERE TABLE_NAME = 'PAR_REGISTRO_MANTENIMIENTO'
     AND COLUMN_NAME = 'REM_ESTADO_RESULTANTE_EMA_ID';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE PAR_REGISTRO_MANTENIMIENTO ADD (REM_ESTADO_RESULTANTE_EMA_ID NUMBER(10))';
  END IF;

  SELECT COUNT(*)
    INTO v_count
    FROM USER_CONSTRAINTS
   WHERE TABLE_NAME = 'PAR_REGISTRO_MANTENIMIENTO'
     AND CONSTRAINT_NAME = 'FK_PAR_REM_ESTADO_RESULTANTE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      ALTER TABLE PAR_REGISTRO_MANTENIMIENTO
      ADD CONSTRAINT FK_PAR_REM_ESTADO_RESULTANTE
      FOREIGN KEY (REM_ESTADO_RESULTANTE_EMA_ID)
      REFERENCES PAR_ESTADO_MAQUINA (EMA_ID)
    ';
  END IF;

  EXECUTE IMMEDIATE '
    UPDATE PAR_REGISTRO_MANTENIMIENTO
       SET REM_TIPO_MOVIMIENTO = ''INICIO''
     WHERE REM_TIPO_MOVIMIENTO IS NULL
  ';

  COMMIT;
END;
/
